Repository artsy/palette, pull requests merged in 2019-07, with the labels that each got.

#529 Adds 100% width to TabsPadding
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Version: Trivial

#532 Fixes justify on Tabs
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Version: Patch

#534 Adds ArrowRightIcon.ios
  packages/palette/src/svgs/ArrowRightIcon.ios.tsx
Labels: Version: Patch

#536 Adds longestText prop to Button component
  packages/palette/src/elements/Button/Button.ios.tsx
  packages/palette/src/elements/Button/Button.shared.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Typography/Typography.tsx
Labels: Merge On Green, Version: Patch

#531 Update to process docs
  packages/palette-docs/content/docs/home/process.mdx
Labels: Version: Patch

#538 Add close icon ios version
  packages/palette/src/svgs/CloseIcon.ios.tsx
Labels: Merge On Green, Version: Patch

#541 Bar chart zero state
  packages/palette/src/elements/BarChart/BarChart.story.tsx
  packages/palette/src/elements/BarChart/BarChart.tsx
Labels: Version: Patch

#542 Minor chart fixes
  packages/palette/src/elements/DataVis/ChartTooltip.tsx
  packages/palette/src/elements/DonutChart/DonutChart.tsx
  packages/palette/src/elements/LineChart/LineChart.tsx
Labels: Version: Patch

#540 PURCHASE-1019 - Adds modal component
  packages/palette-docs/content/docs/elements/dialogs/Modal.mdx
  packages/palette-docs/gatsby-config.js
  packages/palette/src/elements/Modal/Modal.ios.tsx
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/Modal/__tests__/Modal.test.tsx
  packages/palette/src/elements/Modal/index.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/helpers/index.ts
  packages/palette/src/helpers/usePrevious.tsx
  packages/palette/src/svgs/ArtsyLogoBlackIcon.tsx
Labels: Jira Synced, Version: Patch

#545 Adds WIP to modal
  packages/palette-docs/content/docs/elements/dialogs/Modal.mdx
Labels: Version: Patch

#530 Fixes Spring bug and updates Inline to remove padding and height
  packages/palette-docs/content/docs/elements/buttons/Button.mdx
  packages/palette/src/elements/Button/Button.ios.tsx
  packages/palette/src/elements/Button/Button.shared.tsx
  packages/palette/src/elements/Button/Button.tsx
Labels: Merge On Green, Version: Patch

#547 Modal improvements
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/Modal/__tests__/Modal.test.tsx
  packages/palette/src/helpers/index.ts
  packages/palette/src/helpers/usePrevious.tsx
Labels: Version: Patch

#548 Updates button to not always render longestText
  packages/palette/src/elements/Button/Button.tsx
Labels: Merge On Green, Version: Patch

#553 Update Component Spec template to include web Zeplin link
  .github/ISSUE_TEMPLATE/component-spec.md
Labels: Version: Trivial

#546 PURCHASE-1361 Fixes button breaking viewport
  packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx
Labels: Version: Patch
