Repository artsy/palette, pull requests merged in 2019-05, with the labels that each got.

#450 Stop spamming Luc with renovate assignees
  renovate.json
Labels: Merge On Green, Version: Trivial

#451 Revert to old renovate setup
  renovate.json
Labels: Merge On Green, Version: Trivial

#454 Update Buttons “Button”
  packages/palette-docs/content/docs/elements/buttons/Button.mdx
Labels: Docs

#456 Fix some urls in the documentation
  packages/palette-docs/content/docs/home/getting-started.mdx
  packages/palette-docs/content/docs/tokens/Spacing.mdx
Labels: Version: Patch

#457 Use lib workflow
  renovate.json
Labels: Merge On Green, Version: Trivial

#460 Pass disabled prop down to button DOM element
  packages/palette-docs/content/docs/elements/buttons/Button.mdx
  packages/palette/src/elements/Button/Button.test.tsx
  packages/palette/src/elements/Button/Button.tsx
Labels: Merge On Green, Version: Patch

#461 [Menu] Add onClick event type to interface
  packages/palette/src/elements/Menu/Menu.tsx
Labels: Merge On Green, Version: Patch

#462 Passes disabled to Slider
  packages/palette/src/elements/PriceRange/PriceRange.tsx
Labels: Version: Patch

#463 Updates slider disabled styling and allows for disabledText
  packages/palette/src/elements/LabeledRange/LabeledRange.tsx
  packages/palette/src/elements/PriceRange/PriceRange.tsx
  packages/palette/src/elements/Slider/Slider.tsx
Labels: Jira Synced, Version: Patch

#392 X Axis labels for bar chart
  packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
  packages/palette/src/elements/BarChart/Bar.tsx
  packages/palette/src/elements/BarChart/BarChart.test.tsx
  packages/palette/src/elements/BarChart/BarChart.tsx
Labels: Jira Synced, Version: Minor

#466 [Menu] Fix drop shadow
  packages/palette/src/elements/Menu/Menu.tsx
Labels: Merge On Green, Version: Patch

#467 Add a MiniSelect as a select component
  packages/palette-docs/content/docs/elements/inputs/Select.mdx
  packages/palette/src/elements/Select/Select.story.tsx
  packages/palette/src/elements/Select/Select.test.tsx
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#471 Add identifier_field to fix page creation errors
  packages/palette-docs/static/admin/config.js
Labels: Version: Patch

#475 rename MiniSelect to SelectSmall and create separate entry for it in docs
  packages/palette-docs/content/docs/elements/inputs/Select.mdx
  packages/palette-docs/content/docs/elements/inputs/SelectSmall.mdx
  packages/palette/src/elements/Select/Select.story.tsx
  packages/palette/src/elements/Select/Select.test.tsx
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#476 [Link] Add styled-system display mixin
  packages/palette/src/elements/Link/Link.tsx
Labels: Merge On Green, Version: Patch

#477 [Link] Add styled-system position mixin
  packages/palette/src/elements/Link/Link.tsx
Labels: Merge On Green, Version: Patch

#478 remove unused SmallSelect and remove margin/padding on label for SelectSmall
  packages/palette-docs/content/docs/elements/inputs/Select.mdx
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#473 Add the ability to prevent right-click on <Image> elements
  packages/palette-docs/content/docs/elements/images/Image.mdx
  packages/palette/src/elements/Image/Image.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
Labels: Jira Synced, Version: Minor

#480 Add missing component .ios.tsx stubs
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/BarChart/BarChart.ios.tsx
  packages/palette/src/elements/LineChart/LineChart.ios.tsx
  packages/palette/src/platform/primitives.ios.ts
  packages/palette/src/platform/primitives.ts
Labels: Version: Patch

#484 [Docs] Add docs around required palette structure
  packages/palette/README.md
Labels: Docs, Merge On Green, Version: Patch
