Repository artsy/palette, pull requests merged in 2019-04, with the labels that each got.

#361 Add NoImage, Page, and Tag icons
  packages/palette/src/svgs/NoImageIcon.tsx
  packages/palette/src/svgs/PageIcon.tsx
  packages/palette/src/svgs/TagIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#362 Update viewBox of NoImageIcon to fix centering
  packages/palette/src/svgs/NoImageIcon.tsx
Labels: Merge On Green, Version: Patch

#363 Update Buttons “Button”
  packages/palette-docs/content/docs/elements/buttons/Button.mdx
Labels: Docs

#364 If the artwork's highlighted bin is empty, default to showing a minimum-height bar
  packages/palette/src/elements/BarChart/Bar.tsx
  packages/palette/src/elements/BarChart/BarChart.test.tsx
Labels: Version: Patch

#370 Add a safer way to remove extraneous props
  packages/palette/src/elements/Image/Image.shared.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
  packages/palette/src/elements/Tag/Tag.ts
  packages/palette/src/elements/Tag/__tests__/Tag.test.ts
  packages/palette/src/elements/Tag/index.ts
  packages/palette/src/helpers/withoutStyleProps.tsx
  packages/palette/src/platform/primitives.ios.ts
  packages/palette/src/platform/primitives.ts
Labels: Version: Minor

#366 [BarChart] Constrain highlight label position
  packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
  packages/palette/src/elements/BarChart/Bar.tsx
  packages/palette/src/elements/BarChart/BarChart.tsx
Labels: Jira Synced, Version: Patch

#371 Remove test files from published package
  packages/palette/.npmignore
  packages/palette/package.json
Labels: Version: Patch

#372 Resolve issue where some images didn't load when lazy loading
  packages/palette/src/elements/Image/LazyImage.tsx
  packages/palette/src/elements/Tag/Tag.tsx
  packages/palette/src/elements/Tag/index.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Patch

#365 Add background to <Flex>
  packages/palette/src/elements/Flex/Flex.tsx
Labels: Version: Minor

#374 exported BarBox for reaction tests
  packages/palette/src/elements/BarChart/Bar.tsx
Labels: Version: Patch

#375 export Bar.tsx from index
  packages/palette/src/elements/BarChart/index.tsx
Labels: Version: Patch

#376 Generate stylesheet
  packages/palette/package.json
  packages/palette/scripts/generate-styles.ts
  packages/palette/scripts/generate-tokens.test.ts
  packages/palette/scripts/generate-tokens.ts
  packages/palette/tokens.json
Labels: Merge On Green, Version: Minor

#377 creates a docs-only <ColorComponent> to allow display of separate colors
  packages/palette-docs/content/docs/tokens/Color.mdx
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/src/components/ColorComponent.jsx
  packages/palette-docs/src/components/GlobalComponents.jsx
Labels: Version: Patch

#379 Update Tokens “Color”
  packages/palette-docs/content/docs/tokens/Color.mdx
Labels: Docs

#384 Update Images “Avatar”
  packages/palette-docs/content/docs/elements/images/Avatar.mdx
Labels: Docs

#385 Remove mixed content
  packages/palette-docs/content/docs/elements/images/Avatar.mdx
  packages/palette-docs/content/docs/elements/images/Image.mdx
Labels: Docs, Merge On Green

#386 added onHover to barchart bars
  packages/palette/src/elements/BarChart/Bar.tsx
  packages/palette/src/elements/BarChart/BarChart.test.tsx
  packages/palette/src/elements/BarChart/BarChart.tsx
Labels: Version: Patch

#383 Update Inputs “RadioGroup”
  packages/palette-docs/content/docs/elements/inputs/RadioGroup.mdx
Labels: Docs

#381 Update Buttons “Button”
  packages/palette-docs/content/docs/elements/buttons/Button.mdx
Labels: Docs

#389 Tooltip related changes
  packages/palette/src/elements/Tooltip/Tooltip.tsx
  packages/palette/src/svgs/QuestionCircleIcon.tsx
Labels: Version: Patch

#390 fixes ColorComponent admin display and tweaks styling
  packages/palette-docs/content/docs/tokens/Color.mdx
  packages/palette-docs/src/components/GlobalComponents.jsx
Labels: Version: Patch

#391 Reduce payload size by updating moment-timezone
  packages/palette/package.json
  yarn.lock
Labels: Version: Minor

#396 [Menu] Fix drop shadow color
  packages/palette/src/elements/Menu/Menu.tsx
Labels: Merge On Green, Version: Patch

#395 Add triangle to highlighted bar on xs breakpoint
  packages/palette/src/elements/BarChart/Bar.tsx
  packages/palette/src/elements/BarChart/BarChart.tsx
Labels: Jira Synced

#393 only apply cursor pointer to bar if it has onclick
  packages/palette/src/elements/BarChart/Bar.tsx
Labels: Jira Synced, Version: Patch

#398 Add storybooks, visual testing with chromatic
  .circleci/config.yml
  .gitignore
  package.json
  packages/palette/.storybook/addons.js
  packages/palette/.storybook/config.js
  packages/palette/.storybook/preview-head.html
  packages/palette/.storybook/webpack.config.js
  packages/palette/package.json
  packages/palette/src/elements/Avatar/Avatar.story.tsx
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  yarn.lock
Labels: Version: Minor

#399 Auto approve chromatic results on master
  .circleci/config.yml
Labels: Merge On Green, Version: Trivial

#400 Update to use the @artsy:lib renovate workflow
  renovate.json
Labels: Merge On Green, Version: Trivial

#404 Update Buttons “Button”
  packages/palette-docs/content/docs/elements/buttons/Button.mdx
Labels: Docs

#405 [Toolchain] Add @storybook/viewport plugin
  packages/palette/.storybook/addons.js
  packages/palette/.storybook/config.js
  packages/palette/package.json
  yarn.lock
Labels: Version: Patch
