Repository artsy/palette, pull requests merged in 2019-02, with the labels that each got.

#246 Add netlifycms categories
  .vscode/settings.json
  www/content/docs/components/EntityHeader.mdx
  www/content/docs/components/Toggle.mdx
  www/content/pages/CHANGELOG.mdx
  www/gatsby-config.js
  www/gatsby-node.js
  www/package.json
  www/src/cms/cms.jsx
  www/static/admin/config.js
  www/static/admin/config.yml
  www/static/assets/screen-shot-2019-01-30-at-11.36.27-am.png
  www/yarn.lock
Labels: Version: Patch

#247 Add react-helmet
  www/content/pages/CHANGELOG.mdx
  www/gatsby-config.js
  www/package.json
  www/src/Boot.tsx
  www/src/layouts/DefaultLayout.tsx
  www/yarn.lock
Labels: Version: Patch

#249 Make TextArea title and descrption ReactNodes so we can add links etc
  src/elements/TextArea/TextArea.tsx
Labels: Merge On Green, Version: Patch

#250 fix textarea font rendering
  src/elements/TextArea/TextArea.tsx
Labels: Version: Patch

#251 Deploy
  www/gatsby-config.js
  www/src/Boot.tsx
Labels: Version: Patch

#255 Redirect palette traffic to the about page
  www/content/docs/index.mdx
  www/gatsby-node.js
Labels: Merge On Green, Version: Trivial

#256 Use editorial workflow when deployed
  www/static/admin/config.js
Labels: Version: Trivial

#257 Update Home “about”
  www/content/docs/home/about.mdx
Labels: Docs

#259 Fix SSR navigation
  www/gatsby-config.js
  www/gatsby-ssr.js
  www/package.json
  www/src/components/Sidebar/NavState.tsx
  www/src/components/Sidebar/index.tsx
  www/src/layouts/DefaultLayout.tsx
  www/yarn.lock
Labels: Version: Trivial

#261 Polish
  src/elements/Colors/Colors.tsx
  www/content/docs/changelog.mdx
  www/content/docs/elements/animation/index.mdx
  www/content/docs/elements/buttons/Button.mdx
  www/content/docs/home/about.mdx
  www/content/docs/home/changelog.mdx
  www/content/docs/home/getting-started.mdx
  www/content/docs/home/process.mdx
  www/content/docs/tokens/Color.mdx
  www/content/docs/tokens/Grid.mdx
  www/content/docs/tokens/Icons.mdx
  www/content/docs/tokens/Spacing.mdx
  www/content/docs/tokens/Typography.mdx
  www/content/docs/utilities/index.mdx
  www/gatsby-config.js
  www/package.json
  www/src/Boot.tsx
  www/src/components/GlobalComponents.jsx
  www/src/components/Playground.tsx
  www/src/components/Sidebar/NavTree.tsx
  www/src/components/Sidebar/index.tsx
  www/src/layouts/DefaultLayout.tsx
  www/static/admin/config.js
  www/static/assets/color-table.png
  www/static/assets/spacing-base-10.png
  www/static/assets/spacing-size-units.png
  www/yarn.lock
Labels: Version: Trivial

#262 Auto-expand home nav
  src/elements/Colors/Colors.tsx
  www/content/docs/home/about.mdx
  www/content/docs/home/index.mdx
  www/gatsby-node.js
  www/src/components/Sidebar/NavTree.tsx
  www/src/components/Sidebar/index.tsx
Labels: Version: Patch

#263 Bump palette
  www/package.json
  www/yarn.lock
Labels: Version: Patch

#264 Update Home “getting-started”
  www/content/docs/home/getting-started.mdx
Labels: Docs

#265 Move about page up
  www/content/docs/home/about.mdx
  www/content/docs/home/getting-started.mdx
  www/content/docs/index.mdx
  www/content/docs/tokens/index.mdx
  www/gatsby-node.js
  www/package.json
  www/static/admin/config.js
  www/yarn.lock
Labels: Version: Patch

#266 Update Tokens “Spacing”
  www/content/docs/tokens/Spacing.mdx
Labels: Docs

#267 More polish / content
  www/content/docs/elements/buttons/Button.mdx
  www/content/docs/home/getting-started.mdx
  www/content/docs/home/process.mdx
  www/content/docs/index.mdx
  www/content/docs/tokens/Color.mdx
  www/content/docs/tokens/Grid.mdx
  www/content/docs/tokens/Spacing.mdx
  www/content/docs/tokens/Typography.mdx
  www/package.json
  www/src/Boot.tsx
  www/src/components/ArtsyCodeTheme.tsx
  www/src/components/Playground.tsx
  www/yarn.lock
Labels: Version: Trivial

#268 Simplify sharing components / styles with CMS
  www/src/Boot.tsx
  www/src/cms/cms.jsx
  www/src/components/ArtsyCodeTheme.jsx
  www/src/components/GlobalComponents.jsx
  www/src/components/Playground.jsx
  www/static/admin/config.js
Labels: Version: Trivial

#269 Remove old docs 🎉
  .gitignore
  README.md
  docs/Avatar.mdx
  docs/Banner.mdx
  docs/BorderBox.mdx
  docs/Box.mdx
  docs/Button.mdx
  docs/Checkbox.mdx
  docs/Collapse.mdx
  docs/Colors.mdx
  docs/EntityHeader.mdx
  docs/Flex.mdx
  docs/Icons.mdx
  docs/Image.mdx
  docs/Join.mdx
  docs/Link.mdx
  docs/Message.mdx
  docs/Pagination.mdx
  docs/PriceRange.mdx
  docs/ProgressBar.mdx
  docs/ProgressBarTimer.mdx
  docs/Radio.mdx
  docs/RadioGroup.mdx
  docs/ReadMore.mdx
  docs/Select.mdx
  docs/Separator.mdx
  docs/Slider.mdx
  docs/Spacer.mdx
  docs/Spinner.mdx
  docs/StackableBorderBox.mdx
  docs/StaticCountdownTimer.mdx
  docs/Stepper.mdx
  docs/Tabs.mdx
  docs/TimeRemaining.mdx
  docs/Toggle.mdx
  docs/Tooltip.mdx
  docs/Typography.mdx
  docs/index.html
  docs/index.mdx
  docs/utils/components/Wrapper.tsx
  package.json
  www/README.md
  www/content/docs/components/LabeledRange.mdx
  www/content/docs/elements/inputs/Radio.mdx
  www/content/docs/elements/inputs/TextArea.mdx
  www/content/docs/elements/layout/Collapse.mdx
  www/content/docs/elements/layout/ReadMore.mdx
  www/gatsby-config.js
  www/package.json
  www/src/components/GlobalComponents.jsx
  www/src/components/Playground.jsx
  www/yarn.lock
  yarn.lock
Labels: Version: Patch

#270 Remove straggler .doczrc file
  doczrc.js
Labels: Version: Patch

#273 Fill in more content
  src/svgs/Icon.tsx
  www/content/docs/elements/buttons/Link.mdx
  www/content/docs/elements/dialogs/Banner.mdx
  www/content/docs/elements/dialogs/DialogWindow.mdx
  www/content/docs/elements/dialogs/Message.mdx
  www/content/docs/elements/images/Avatar.mdx
  www/content/docs/elements/images/Image.mdx
  www/content/docs/elements/inputs/Checkbox.mdx
  www/content/docs/elements/inputs/Input.mdx
  www/content/docs/elements/inputs/RadioGroup.mdx
  www/content/docs/elements/inputs/Select.mdx
  www/content/docs/elements/inputs/Slider.mdx
  www/content/docs/elements/inputs/Tooltip.mdx
  www/content/docs/elements/navigation/Pagination.mdx
  www/content/docs/elements/navigation/Stepper.mdx
  www/content/docs/elements/navigation/Tabs.mdx
  www/content/docs/tokens/Grid.mdx
  www/src/components/Playground.jsx
Labels: Version: Patch

#274 Add Netlify status badge
  README.md
Labels: Version: Trivial

#276 Expand first level nav items on load
  www/content/docs/components/index.mdx
  www/content/docs/elements/index.mdx
  www/content/docs/tokens/index.mdx
  www/content/docs/utilities/index.mdx
  www/src/components/Sidebar/NavTree.tsx
Labels: Version: Trivial

#277 Flip chevrons on nav
  www/src/components/Sidebar/NavTree.tsx
Labels: Version: Patch

#278 [Icon] fix props
  src/svgs/ClosedEyeIcon.tsx
Labels: Version: Patch

#280 Address Design QA
  www/content/docs/components/EntityHeader.mdx
  www/content/docs/elements/animation/index.mdx
  www/content/docs/elements/dialogs/Banner.mdx
  www/content/docs/elements/dialogs/DialogWindow.mdx
  www/content/docs/elements/inputs/Input.mdx
  www/content/docs/elements/inputs/QuickInput.mdx
  www/content/docs/elements/layout/Collapse.mdx
  www/content/docs/home/component-checklist.mdx
  www/content/docs/home/getting-started.mdx
  www/content/docs/home/process.mdx
  www/content/docs/index.mdx
  www/content/docs/tokens/Icons.mdx
  www/content/docs/utilities/index.mdx
  www/src/Boot.tsx
  www/src/components/GlobalComponents.jsx
  www/src/components/Sidebar/NavTree.tsx
  www/src/components/Sidebar/index.tsx
  www/src/components/StatusBadge.tsx
  www/src/layouts/DefaultLayout.tsx
  www/static/admin/config.js
  www/static/admin/config.yml
Labels: Version: Patch

#282 Back to black
  www/src/components/GlobalComponents.jsx
Labels: Version: Patch

#180 [Lib] Bump styled-components 4.0.3
  package.json
  src/elements/TextArea/__tests__/TextArea.test.tsx
  src/helpers/injectGlobalStyles.tsx
  yarn.lock
Labels: Version: Major

#285 updates docs command with yarn install
  package.json
Labels: Merge On Green, Version: Trivial

#286 moves www onto styled components 4
  www/package.json
  www/src/Boot.tsx
  www/src/layouts/DefaultLayout.tsx
  www/yarn.lock
Labels: Version: Trivial

#288 Add babel-plugin-add-react-displayname
  .babelrc
  package.json
  yarn.lock
Labels: Version: Patch

#290 Add `label` prop to Radio
  src/elements/Radio/Radio.tsx
  www/content/docs/elements/inputs/Radio.mdx
  www/content/docs/elements/inputs/RadioGroup.mdx
Labels: Version: Patch

#294 The Link color was not used properly in docs. Correcting that.
  www/content/docs/elements/buttons/Link.mdx
Labels: Version: Trivial

#297 Optimizing svgs
  src/svgs/CircleBlackCheckIcon.tsx
  src/svgs/CircleWhiteCheckIcon.tsx
  src/svgs/CloseIcon.tsx
  src/svgs/DownloadIcon.tsx
  src/svgs/EditIcon.tsx
  src/svgs/GenomeIcon.tsx
  src/svgs/HelpIcon.tsx
  src/svgs/LocationIcon.tsx
  src/svgs/MoreIcon.tsx
  src/svgs/OpenEyeIcon.tsx
  src/svgs/PlusIcon.tsx
  src/svgs/ShareIcon.tsx
Labels: Jira Synced

#302 Replace `StaticQuery` with Hooks / Upgrade gatsby@2.1.0
  www/package.json
  www/src/components/Sidebar/NavTree.tsx
  www/yarn.lock
Labels: Version: Patch

#303 Add types to Icons
  src/svgs/AuctionIcon.tsx
  src/svgs/BellIcon.tsx
  src/svgs/BlueChipIcon.tsx
  src/svgs/BookIcon.tsx
  src/svgs/CheckIcon.tsx
  src/svgs/CircleBlackCheckIcon.tsx
  src/svgs/CircleWhiteCheckIcon.tsx
  src/svgs/CloseIcon.tsx
  src/svgs/ClosedEyeIcon.tsx
  src/svgs/CreditCardIcon.tsx
  src/svgs/DownloadIcon.tsx
  src/svgs/EditIcon.tsx
  src/svgs/FacebookIcon.tsx
  src/svgs/FairIcon.tsx
  src/svgs/FilterIcon.tsx
  src/svgs/GenomeIcon.tsx
  src/svgs/GroupIcon.tsx
  src/svgs/HeartIcon.tsx
  src/svgs/HelpIcon.tsx
  src/svgs/Icon.tsx
  src/svgs/InstagramIcon.tsx
  src/svgs/LocationIcon.tsx
  src/svgs/LockIcon.tsx
  src/svgs/LosingBidIcon.tsx
  src/svgs/MoreIcon.tsx
  src/svgs/MuseumIcon.tsx
  src/svgs/OpenEyeIcon.tsx
  src/svgs/Pageviews.tsx
  src/svgs/PlusIcon.tsx
  src/svgs/ShareIcon.tsx
  src/svgs/SoloIcon.tsx
  src/svgs/TimerIcon.tsx
  src/svgs/TopEmergingIcon.tsx
  src/svgs/TopEstablishedIcon.tsx
  src/svgs/TwitterIcon.tsx
  src/svgs/WeChatIcon.tsx
  src/svgs/WinningBidIcon.tsx
Labels: Version: Patch

#304 Add optional size type
  src/svgs/ClosedEyeIcon.tsx
Labels: Version: Patch
