Repository artsy/palette, pull requests merged in 2019-08, with the labels that each got.

#556 Doesn't render modal in DOM if it's offscreen
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Merge On Green

#557 Fixes entityheader subtext size
  packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx
Labels: Version: Patch

#561 [EntityHeader] Add onClick handler #trivial
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
Labels: Version: Patch

#562 [EntityHeader] Fix interface definition #trivial
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
Labels: Merge On Green, Version: Patch

#565 Small CSS adjustments to modal for scroll
  packages/palette-docs/content/docs/elements/dialogs/Modal.mdx
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Version: Patch

#564 Creates TimeRemaing.ios.tsx and updates TimeRemaining API
  README.md
  packages/palette-docs/content/docs/components/StaticCountdownTimer.mdx
  packages/palette-docs/content/docs/components/TimeRemaining.mdx
  packages/palette/src/elements/ProgressBarTimer/ProgressBarTimer.tsx
  packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  packages/palette/src/elements/StaticCountdownTimer/__tests__/StaticCountdownTimer.test.tsx
  packages/palette/src/elements/TimeRemaining/TimeRemaining.ios.tsx
  packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
  packages/palette/src/elements/TimeRemaining/__tests__/TimeRemaining.test.tsx
  packages/palette/src/utils/useCurrentTime.ts
  packages/palette/src/utils/useInterval.ts
Labels: Version: Patch

#563 New CSSGrid element
  packages/palette-docs/content/docs/elements/layout/CSSGrid.mdx
  packages/palette-docs/content/docs/elements/layout/Grid.mdx
  packages/palette/src/elements/CSSGrid/CSSGrid.ios.tsx
  packages/palette/src/elements/CSSGrid/CSSGrid.story.tsx
  packages/palette/src/elements/CSSGrid/CSSGrid.tsx
  packages/palette/src/elements/CSSGrid/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor

#566 Adds fontsize props to TimeRemaining
  packages/palette-docs/content/docs/components/TimeRemaining.mdx
  packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
Labels: Version: Patch

#567 [ReadMore] Add disabled prop
  packages/palette/src/elements/ReadMore/ReadMore.story.tsx
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx
Labels: Version: Minor

#568 [RadioGroup] Fix defaultValue selection #trivial
  packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.tsx
Labels: Version: Patch

#569 Adds ios Close and Check Circle Icons
  packages/palette/package.json
  packages/palette/src/svgs/CheckCircleIcon.ios.tsx
  packages/palette/src/svgs/CloseCircleIcon.ios.tsx
  yarn.lock
Labels: Version: Patch
