Repository artsy/palette, pull requests merged in 2019-01, with the labels that each got.

#148 Update auto-release to v2
  .autorc
  package.json
  yarn.lock
Labels: Version: Trivial

#147 Simplify circleci config by relying on orbs
  .circleci/config.yml
Labels: Version: Trivial

#157 Updates readme
  README.md
Labels: Merge On Green, Version: Patch

#158 [Helper] Add injectGlobalStyles helper
  src/helpers/injectGlobalStyles.tsx
Labels: Version: Minor

#159 [Helper] Add missing export
  src/helpers/index.ts
Labels: Merge On Green, Version: Patch

#160 [Docs v2] Add Gatsby
  docs2/.eslintrc
  docs2/.gitignore
  docs2/LICENSE
  docs2/README.md
  docs2/gatsby-browser.js
  docs2/gatsby-config.js
  docs2/gatsby-node.js
  docs2/gatsby-ssr.js
  docs2/package.json
  docs2/src/Boot.tsx
  docs2/src/components/Header.tsx
  docs2/src/components/Layout.tsx
  docs2/src/pages/404.tsx
  docs2/src/pages/PageTwo.tsx
  docs2/src/pages/index.tsx
  docs2/tsconfig.json
  docs2/tslint.json
  docs2/yarn.lock
Labels: Merge On Green, Version: Trivial

#163 Fixes Banner styling
  src/elements/Banner/Banner.test.tsx
  src/elements/Banner/Banner.tsx
Labels: Version: Patch

#167 [Renovate] Ignore docs2 folder
  renovate.json
Labels: Version: Trivial

#168 [Icons] Add Reaction SVG icons
  src/svgs/Auction.tsx
  src/svgs/Bell.tsx
  src/svgs/BlueChip.tsx
  src/svgs/Book.tsx
  src/svgs/CheckIcon.tsx
  src/svgs/ChevronIcon.tsx
  src/svgs/CircleBlackCheckIcon.tsx
  src/svgs/CircleWhiteCheckIcon.tsx
  src/svgs/ClosedEye.tsx
  src/svgs/Download.tsx
  src/svgs/Edit.tsx
  src/svgs/Fair.tsx
  src/svgs/FilterIcon.tsx
  src/svgs/Genome.tsx
  src/svgs/Group.tsx
  src/svgs/Heart.tsx
  src/svgs/Help.tsx
  src/svgs/Location.tsx
  src/svgs/LosingBid.tsx
  src/svgs/Museum.tsx
  src/svgs/OpenEye.tsx
  src/svgs/PlusIcon.tsx
  src/svgs/Share.tsx
  src/svgs/Solo.tsx
  src/svgs/TopEmerging.tsx
  src/svgs/TopEstablished.tsx
  src/svgs/WinningBid.tsx
  src/svgs/index.tsx
Labels: Version: Minor

#170 Add missing Icon export
  src/svgs/index.tsx
Labels: Version: Patch

#171 Add missing Icon export
  src/svgs/index.tsx
Labels: Version: Patch

#172 Add another bucket of icons
  docs/Icons.mdx
  package.json
  src/svgs/ArtsyLogoIcons.tsx
  src/svgs/ChevronIcon.tsx
  src/svgs/CreditCardIcon.tsx
  src/svgs/FacebookIcon.tsx
  src/svgs/Icon.tsx
  src/svgs/InstagramIcon.tsx
  src/svgs/LockIcon.tsx
  src/svgs/Pageviews.tsx
  src/svgs/TimerIcon.tsx
  src/svgs/TwitterIcon.tsx
  src/svgs/WeChatIcon.tsx
  src/svgs/index.tsx
  yarn.lock
Labels: Version: Patch

#173 Add Icon export
  src/svgs/index.tsx
Labels: Version: Patch

#174 Fix icon default export
  src/svgs/LockIcon.tsx
Labels: Version: Patch

#175 [Lib] Upgrade husky
  package.json
  src/svgs/LockIcon.tsx
  yarn.lock
Labels: Version: Patch

#176 Fix box-sizing issue in global css
  package.json
  src/elements/Checkbox/Checkbox.tsx
  src/helpers/injectGlobalStyles.tsx
  src/svgs/CheckIcon.tsx
  src/svgs/CheckIcon2.tsx
  src/svgs/index.tsx
  yarn.lock
Labels: Version: Patch

#179 Move grid over from reaction
  package.json
  src/elements/Grid/Grid.ios.tsx
  src/elements/Grid/Grid.tsx
  src/elements/Grid/index.ts
  src/elements/index.tsx
  tsconfig.json
  yarn.lock
Labels: Version: Patch

#187 Remove auto-release-cli as a dependency
  package.json
  yarn.lock
Labels: Version: Trivial

#188 Make trivial considered an internal change
  .autorc
Labels: Version: Trivial

#189 Don't deploy trivial changes
  .autorc
Labels: Version: Trivial

#191 [Elements] Move Tabs and Toggle from Reaction
  docs/Tabs.mdx
  docs/Toggle.mdx
  src/elements/Tabs/Tabs.ios.tsx
  src/elements/Tabs/Tabs.tsx
  src/elements/Tabs/__tests__/Tabs.test.tsx
  src/elements/Tabs/index.tsx
  src/elements/Toggle/Toggle.ios.tsx
  src/elements/Toggle/Toggle.tsx
  src/elements/Toggle/__tests__/Toggle.test.tsx
  src/elements/Toggle/index.tsx
  src/elements/index.tsx
Labels: Version: Minor

#192 Make Tabs export name more descriptive
  src/elements/Tabs/Tabs.tsx
Labels: Version: Patch

#195 [Docs v2] Continue static layout
  doczrc.js
  www/package.json
  www/src/components/StatusBadge.tsx
  www/src/pages/index.tsx
  www/src/pages/layout.tsx
  www/yarn.lock
Labels: Version: Trivial

#197 Start building out dynamic page generation logic
  README.md
  www/gatsby-config.js
  www/gatsby-node.js
  www/package.json
  www/src/components/Layout.tsx
  www/src/pages/404.tsx
  www/src/pages/PageTwo.tsx
  www/src/pages/components/Avatar.mdx
  www/src/pages/index.tsx
  www/src/pages/test.mdx
  www/static/favicon.ico
  www/system/onCreateNode.js
  www/system/onCreateWebpackConfig.js
  www/tsconfig.json
  www/yarn.lock
Labels: Version: Trivial

#199 Migrate PriceRange component from Reaction
  docs/PriceRange.mdx
  src/elements/PriceRange/PriceRange.ios.tsx
  src/elements/PriceRange/PriceRange.tsx
  src/elements/PriceRange/index.tsx
  src/elements/index.tsx
Labels: Version: Patch

#202 Add EntityHeader component
  docs/EntityHeader.mdx
  src/elements/EntityHeader/EntityHeader.ios.tsx
  src/elements/EntityHeader/EntityHeader.tsx
  src/elements/EntityHeader/index.tsx
  src/elements/Link/Link.tsx
  src/elements/index.tsx
Labels: Version: Minor

#203 Migrate TimeRemaining component from Reaction
  docs/TimeRemaining.mdx
  package.json
  src/elements/TimeRemaining/TimeRemaining.ios.tsx
  src/elements/TimeRemaining/TimeRemaining.tsx
  src/elements/TimeRemaining/index.tsx
  src/elements/index.tsx
  yarn.lock
Labels: Version: Minor

#198 Migrate Pagination Components from Reaction (SELL-862)
  docs/Pagination.mdx
  src/elements/Pagination/Pagination.ios.tsx
  src/elements/Pagination/Pagination.tsx
  src/elements/Pagination/index.tsx
  src/elements/index.tsx
Labels: Jira Synced, Version: Minor

#204 Migrate progress bar from reaction
  docs/PriceRange.mdx
  docs/ProgressBar.mdx
  docs/ProgressBarTimer.mdx
  src/elements/ProgressBar/ProgressBar.ios.tsx
  src/elements/ProgressBar/ProgressBar.tsx
  src/elements/ProgressBar/index.tsx
  src/elements/ProgressBarTimer/ProgressBarTimer.ios.tsx
  src/elements/ProgressBarTimer/ProgressBarTimer.tsx
  src/elements/ProgressBarTimer/index.tsx
  src/elements/index.tsx
Labels: Version: Minor

#205 Migrate StaticCountdownTimer from Reaction
  docs/StaticCountdownTimer.mdx
  package.json
  src/elements/ProgressBarTimer/ProgressBarTimer.tsx
  src/elements/StaticCountdownTimer/StaticCountdownTimer.ios.tsx
  src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  src/elements/StaticCountdownTimer/index.tsx
  src/elements/index.tsx
  yarn.lock
Labels: Version: Minor

#206 Fix pagination arrow alignment
  src/elements/Pagination/Pagination.tsx
  src/svgs/ChevronIcon.tsx
Labels: Version: Patch

#207 Move Pagination tests
  src/elements/Pagination/Pagination.tsx
  src/elements/Pagination/__tests__/Pagination.test.tsx
Labels: Version: Patch

#208 Add ability to pass styles to injectGlobal
  src/helpers/injectGlobalStyles.tsx
Labels: Version: Minor

#209 [Docs 2] Add dynamic page navigation + break apart page components
  www/config/onCreateNode.js
  www/config/onCreateWebpackConfig.js
  www/gatsby-browser.js
  www/gatsby-config.js
  www/gatsby-node.js
  www/gatsby-ssr.js
  www/package.json
  www/src/Boot.tsx
  www/src/components/ContentArea.tsx
  www/src/components/Header.tsx
  www/src/components/Layout.tsx
  www/src/components/PropsTable.tsx
  www/src/components/Sidebar.tsx
  www/src/pages/PageTwo.tsx
  www/src/pages/components/Avatar.mdx
  www/src/pages/elements/avatar.mdx
  www/src/pages/layout.tsx
  www/src/pages/test.mdx
  www/src/utils/pathListToTree.ts
  www/tsconfig.json
  www/yarn.lock
Labels: Version: Patch

#211 [Docs v2] Implement rough code editor
  .vscode/settings.json
  package.json
  www/config/onCreateNode.js
  www/config/onCreateWebpackConfig.js
  www/gatsby-browser.js
  www/gatsby-config.js
  www/gatsby-node.js
  www/package.json
  www/src/Boot.tsx
  www/src/components/ContentArea.tsx
  www/src/components/Layout.tsx
  www/src/components/Playground.tsx
  www/src/components/Sidebar.tsx
  www/src/components/Sidebar/NavTree.tsx
  www/src/components/Sidebar/index.tsx
  www/src/components/StatusBadge.tsx
  www/src/pages/elements/avatar.mdx
  www/src/pages/elements/hello.md
  www/src/pages/index.tsx
  www/src/utils/pathListToTree.ts
  www/src/utils/playgroundHastPlugin.js
  www/yarn.lock
  yarn.lock
Labels: Version: Patch

#212 Cleanup directory structure; add dynamic pages
  www/gatsby-browser.js
  www/gatsby-config.js
  www/gatsby-node.js
  www/gatsby-ssr.js
  www/package.json
  www/src/app/Boot.tsx
  www/src/app/components/ContentArea.tsx
  www/src/app/components/Layout.tsx
  www/src/app/components/Playground.tsx
  www/src/app/components/PropsTable.tsx
  www/src/app/components/Sidebar/NavTree.tsx
  www/src/app/components/Sidebar/index.tsx
  www/src/app/components/StatusBadge.tsx
  www/src/app/templates/DocsTemplate.tsx
  www/src/app/utils/pathListToTree.ts
  www/src/app/utils/playgroundHastPlugin.js
  www/src/components/Layout.tsx
  www/src/components/Playground.tsx
  www/src/design-system/elements/avatar.mdx
  www/src/design-system/elements/hello.md
  www/src/pages/404.tsx
  www/src/pages/index.tsx
  www/yarn.lock
Labels: Version: Trivial

#210 Migrate Stepper from Reaction
  docs/Stepper.mdx
  src/elements/Stepper/Stepper.ios.tsx
  src/elements/Stepper/Stepper.tsx
  src/elements/Stepper/__tests__/Stepper.test.tsx
  src/elements/Stepper/index.tsx
  src/elements/Tabs/Tabs.tsx
  src/elements/index.tsx
Labels: Merge On Green, Version: Minor

#218 Update OpenEyeIcon
  docs/Icons.mdx
  src/svgs/OpenEyeIcon.tsx
Labels: Version: Patch

#220 Add barebones Netlify CMS
  package.json
  www/gatsby-config.js
  www/package.json
  www/src/components/Playground.tsx
  www/static/admin/config.yml
  www/yarn.lock
  yarn.lock
Labels: Version: Trivial

#221 @damassi => [CheckIcon] Allow arbitrary styles to be passed in and applied to icon
  src/svgs/CheckIcon.tsx
Labels: Merge On Green, Version: Patch

#222 @damassi => [OpenEyeIcon] Update props to include onClick, and camelcase some SVG…
  src/svgs/OpenEyeIcon.tsx
Labels: Version: Patch

#223 @mzikherman => [OpenEyeIcon] Convert one more SVG prop to camelcase
  src/svgs/OpenEyeIcon.tsx
Labels: Merge On Green, Version: Patch

#224 Add labeled range component
  docs/LabeledRange.mdx
  src/elements/LabeledRange/LabeledRange.ios.tsx
  src/elements/LabeledRange/LabeledRange.tsx
  src/elements/LabeledRange/index.tsx
  src/elements/PriceRange/PriceRange.tsx
  src/elements/index.tsx
Labels: Jira Synced, Version: Patch

#225 @damassi => [OpenEyeIcon] Correct signature for onClick
  src/svgs/OpenEyeIcon.tsx
Labels: Version: Patch

#226 Add Netlify local filesystem support
  www/content/blog/asdf.md
  www/gatsby-config.js
  www/package.json
  www/src/cms/cms.js
  www/static/admin/config.yml
  www/static/assets/media/logo.svg
  www/yarn.lock
Labels: Version: Patch

#227 Add NetlifyCMS .mdx support
  www/content/articles/hi.mdx
  www/content/blog/asdf.md
  www/gatsby-config.js
  www/package.json
  www/src/Boot.tsx
  www/src/cms/cms.js
  www/src/cms/cms.jsx
  www/src/components/GlobalComponents.jsx
  www/static/admin/config.yml
  www/yarn.lock
Labels: Version: Patch

#228 Add CHANGELOG page
  www/content/docs/dialogs/index.mdx
  www/content/docs/forms/index.mdx
  www/content/docs/layout/BorderBox.mdx
  www/content/docs/layout/Box.mdx
  www/content/docs/layout/Collapse.mdx
  www/content/docs/layout/Flex.mdx
  www/content/docs/layout/Join.mdx
  www/content/docs/layout/Separator.mdx
  www/content/docs/layout/Spacer.mdx
  www/content/docs/layout/StackableBorderBox.mdx
  www/content/docs/layout/index.mdx
  www/content/docs/navigation/Pagination.mdx
  www/content/docs/navigation/index.mdx
  www/content/docs/utilities/index.mdx
  www/content/pages/CHANGELOG.mdx
  www/content/pages/change-log.mdx
  www/content/pages/home.mdx
  www/gatsby-config.js
  www/package.json
  www/src/cms/cms.jsx
  www/src/layouts/DefaultLayout.tsx
  www/src/utils/copyChangelog.js
  www/static/admin/config.yml
  www/yarn.lock
Labels: Version: Trivial

#229 Update CMS preview pane
  www/content/articles/hi.mdx
  www/content/blog/asdf.md
  www/content/pages/CHANGELOG.mdx
  www/src/cms/cms.jsx
  www/static/admin/config.yml
Labels: Version: Patch

#231 @mzikherman => [CheckIcon] Add onClick prop
  src/svgs/CheckIcon.tsx
Labels: Merge On Green, Version: Patch

#230 adds ReadMore component to Palette
  docs/ReadMore.mdx
  package.json
  src/elements/ReadMore/ReadMore.ios.tsx
  src/elements/ReadMore/ReadMore.tsx
  src/elements/ReadMore/__tests__/ReadMore.test.tsx
  src/elements/ReadMore/index.tsx
  src/elements/index.tsx
  yarn.lock
Labels: Version: Minor

#233 Use shared autorc config
  .autorc
  package.json
  yarn.lock
Labels: Merge On Green, Version: Trivial

#235 Add script to generate a tokens file
  package.json
  scripts/generate-tokens.test.ts
  scripts/generate-tokens.ts
  tokens.json
  yarn.lock
Labels: Version: Minor

#236 Remove separator from pagination component
  src/elements/Pagination/Pagination.tsx
Labels: Merge On Green, Version: Patch

#237 Adds MoreIcon
  docs/Icons.mdx
  src/svgs/MoreIcon.tsx
  src/svgs/index.tsx
Labels: Version: Patch

#238 Fix MoreIcon dom properties
  src/svgs/MoreIcon.tsx
Labels: Version: Patch

#240 Organize
  www/content/docs/components/EntityHeader.mdx
  www/content/docs/components/PriceRange.mdx
  www/content/docs/components/Toggle.mdx
  www/content/docs/components/index.mdx
  www/content/docs/elements/animation/index.mdx
  www/content/docs/elements/buttons/Button.mdx
  www/content/docs/elements/buttons/Link.mdx
  www/content/docs/elements/buttons/index.mdx
  www/content/docs/elements/dialogs/Banner.mdx
  www/content/docs/elements/dialogs/Message.mdx
  www/content/docs/elements/dialogs/ProgressBar.mdx
  www/content/docs/elements/dialogs/ProgressBarTimer.mdx
  www/content/docs/elements/dialogs/StaticCountdownTimer.mdx
  www/content/docs/elements/dialogs/TimeRemaining.mdx
  www/content/docs/elements/dialogs/index.mdx
  www/content/docs/elements/images/Avatar.mdx
  www/content/docs/elements/images/Image.mdx
  www/content/docs/elements/images/index.mdx
  www/content/docs/elements/index.mdx
  www/content/docs/elements/inputs/Checkbox.mdx
  www/content/docs/elements/inputs/Input.mdx
  www/content/docs/elements/inputs/QuickInput.mdx
  www/content/docs/elements/inputs/Radio.mdx
  www/content/docs/elements/inputs/RadioGroup.mdx
  www/content/docs/elements/inputs/Select.mdx
  www/content/docs/elements/inputs/Slider.mdx
  www/content/docs/elements/inputs/Tooltip.mdx
  www/content/docs/elements/inputs/index.mdx
  www/content/docs/elements/layout/BorderBox.mdx
  www/content/docs/elements/layout/Box.mdx
  www/content/docs/elements/layout/Collapse.mdx
  www/content/docs/elements/layout/Flex.mdx
  www/content/docs/elements/layout/Join.mdx
  www/content/docs/elements/layout/ReadMore.mdx
  www/content/docs/elements/layout/Separator.mdx
  www/content/docs/elements/layout/Spacer.mdx
  www/content/docs/elements/layout/StackableBorderBox.mdx
  www/content/docs/elements/layout/index.mdx
  www/content/docs/elements/loaders/Spinner.mdx
  www/content/docs/elements/loaders/index.mdx
  www/content/docs/elements/navigation/Pagination.mdx
  www/content/docs/elements/navigation/Stepper.mdx
  www/content/docs/elements/navigation/Tabs.mdx
  www/content/docs/elements/navigation/index.mdx
  www/content/docs/forms/index.mdx
  www/content/docs/home/about.mdx
  www/content/docs/home/changelog.mdx
  www/content/docs/tokens/Color.mdx
  www/content/docs/tokens/Grid.mdx
  www/content/docs/tokens/Icons.mdx
  www/content/docs/tokens/Spacing.mdx
  www/content/docs/tokens/Typography.mdx
  www/content/docs/utilities/index.mdx
  www/content/pages/CHANGELOG.mdx
Labels: Version: Patch

#244 New component: TextArea
  docs/TextArea.mdx
  package.json
  src/elements/TextArea/TextArea.tsx
  src/elements/TextArea/__tests__/TextArea.test.tsx
  src/elements/TextArea/index.tsx
  src/elements/Typography/Typography.tsx
  src/elements/index.tsx
  yarn.lock
Labels: Jira Synced, Version: Minor

#245 Add placeholder to TextArea component
  docs/TextArea.mdx
  src/elements/TextArea/TextArea.tsx
Labels: Version: Patch
