Repository artsy/palette, pull requests merged in 2019-10, with the labels that each got.

#598 [Slider] Fix handles
  packages/palette-docs/content/docs/elements/inputs/Slider.mdx
  packages/palette/src/elements/Slider/Slider.story.tsx
  packages/palette/src/elements/Slider/Slider.tsx
Labels: Version: Patch

#596 SelectSmall updates
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#597 Add dialog to palette
  packages/palette-docs/content/docs/elements/dialogs/Dialog.mdx
  packages/palette-docs/content/docs/elements/dialogs/DialogWindow.mdx
  packages/palette/src/elements/Dialog/Dialog.ios.tsx
  packages/palette/src/elements/Dialog/Dialog.story.tsx
  packages/palette/src/elements/Dialog/Dialog.tsx
  packages/palette/src/elements/Dialog/__tests__/Dialog.test.tsx
  packages/palette/src/elements/Dialog/index.tsx
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Patch

#601 bug fix for Dialog
  packages/palette/src/elements/Dialog/Dialog.tsx
Labels: Version: Patch

#600 Improve selects
  packages/palette-docs/content/docs/elements/inputs/Input.mdx
  packages/palette-docs/content/docs/elements/inputs/Select.mdx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Select/Select.story.tsx
  packages/palette/src/elements/Select/Select.test.tsx
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#602 Export the Option interface
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#603 Allow attributes to be passed to checkbox for testing
  packages/palette/src/elements/Checkbox/Checkbox.tsx
Labels: Version: Patch

#607 Rename `Tag` -> `CleanTag`
  packages/palette/src/elements/CleanTag/CleanTag.tsx
  packages/palette/src/elements/CleanTag/__tests__/CleanTag.test.ts
  packages/palette/src/elements/CleanTag/index.tsx
  packages/palette/src/elements/Image/Image.shared.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
  packages/palette/src/elements/Tag/index.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Major

#608 [PURCHASE-1577] Tag component
  packages/palette-docs/content/docs/elements/Tags.mdx
  packages/palette/src/elements/Tags/Tags.story.tsx
  packages/palette/src/elements/Tags/Tags.tsx
  packages/palette/src/elements/Tags/__tests__/Tags.test.tsx
  packages/palette/src/elements/Tags/index.tsx
  packages/palette/src/elements/index.tsx
Labels: Jira Synced, Version: Minor

#609 Add maxWidth to selects
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#611 Make Tags cross platform
  packages/palette/src/elements/Tags/Tags.tsx
Labels: Merge On Green, Version: Patch

#606 PURCHASE-1518: Update Bell and BellFill Icons in Palette
  packages/palette/src/svgs/BellFillIcon.tsx
  packages/palette/src/svgs/BellIcon.tsx
Labels: Jira Synced

#612 Removes extra fragment.
  packages/palette/src/elements/Tags/Tags.tsx
Labels: Merge On Green, Version: Patch
