Repository artsy/palette, pull requests merged in 2019-06, with the labels that each got.

#486 [ReactNative] Create more stub components
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/Input/Input.ios.tsx
  packages/palette/src/elements/TextArea/TextArea.ios.tsx
  packages/palette/src/helpers/isReactNative.tsx
  packages/palette/src/svgs/Icon.ios.tsx
  packages/palette/src/svgs/WeChatIcon.ios.tsx
Labels: Merge On Green, Version: Patch

#487 [Debug] Test deploy
  packages/palette/src/Theme.tsx
Labels: Version: Patch

#488 Support Flexbox order
  packages/palette-docs/content/docs/elements/layout/Flex.mdx
  packages/palette/src/elements/Flex/Flex.tsx
Labels: Version: Minor

#491 Add ios type-checking
  packages/palette/package.json
  packages/palette/tsconfig.ios.json
Labels: Version: Trivial

#494 Add react-native-svg to peerDependencies
  packages/palette/package.json
  yarn.lock
Labels: Version: Trivial

#496 Fix error when all linechart values are zero
  packages/palette/src/elements/LineChart/LineChartSVG.tsx
Labels: Merge On Green, Version: Patch

#501 Small fix in StaticCountdownTimer hour logic
  packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  packages/palette/src/elements/StaticCountdownTimer/__tests__/StaticCountdownTimer.test.tsx
Labels: Merge On Green, Version: Patch

#502 Updates to Luxon logic
  packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  packages/palette/src/elements/StaticCountdownTimer/__tests__/StaticCountdownTimer.test.tsx
  packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
  packages/palette/src/elements/TimeRemaining/__tests__/TimeRemaining.test.tsx
Labels: Version: Patch

#503 [Menu] Make width adjustable
  packages/palette/src/elements/Menu/Menu.tsx
Labels: Version: Patch

#506 Add README section for linking/unlinking with Reaction
  README.md
Labels: Merge On Green

#508 Allow any 1.x version of luxon
  packages/palette/package.json
Labels: Merge On Green, Version: Patch

#511 [Lib] Upgrade react-spring@8.0.23
  packages/palette/.storybook/config.js
  packages/palette/package.json
  packages/palette/src/elements/BarChart/BarChart.story.tsx
  packages/palette/src/elements/Collapse/Collapse.ios.tsx
  packages/palette/src/elements/DonutChart/DonutChart.tsx
  packages/palette/src/elements/LineChart/LineChart.story.tsx
  packages/palette/src/elements/LineChart/LineChartSVG.tsx
  yarn.lock
Labels: Version: Patch

#509 PURCHASE-1060/PURCHASE-1059: iOs Entity Header palette component
  packages/palette/src/elements/Avatar/Avatar.ios.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx
Labels: Version: Patch

#479 Update Home “process”
  packages/palette-docs/content/docs/home/process.mdx
Labels: Docs

#474 Create Home “naming”
  packages/palette-docs/content/docs/home/naming.mdx
Labels: Docs

#512 Moves luxon to dependency
  packages/palette/package.json
  yarn.lock
Labels: Version: Patch

#515 Button & Spinner Component for React Native
  packages/palette/src/elements/Button/Button.ios.tsx
  packages/palette/src/elements/Button/Button.shared.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Button/index.tsx
  packages/palette/src/elements/Spinner/Spinner.ios.tsx
  packages/palette/src/elements/Spinner/Spinner.shared.tsx
  packages/palette/src/elements/Spinner/Spinner.tsx
  packages/palette/src/elements/Spinner/index.tsx
Labels: Version: Patch

#469 Update Inputs “Select”
  packages/palette-docs/content/docs/elements/inputs/Select.mdx
Labels: Docs

#468 Update Inputs “Input”
  packages/palette-docs/content/docs/elements/inputs/Input.mdx
Labels: Docs

#513 Adds repos consuming palette to readme
  README.md
Labels: Docs, Merge On Green

#516 Fix import path
  packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
  packages/palette/src/elements/Button/Button.ios.tsx
Labels: Version: Patch

#517 Adds LineChart props type export
  packages/palette/src/elements/LineChart/LineChart.tsx
Labels: Version: Patch

#519 Fix donut chart animation bug
  packages/palette/src/elements/DonutChart/DonutChart.tsx
Labels: Jira Synced, Version: Patch

#520 Fixes typo
  packages/palette/src/elements/Avatar/Avatar.ios.tsx
Labels: Merge On Green, Version: Trivial

#523 Add prop to make button full width
  packages/palette/src/elements/Button/Button.ios.tsx
  packages/palette/src/elements/Button/Button.shared.tsx
Labels: Merge On Green, Version: Patch

#524 Adds note about Zeppelin plugin
  README.md
Labels: Version: Patch

#526 Adds padding to small button
  packages/palette/src/elements/Button/Button.tsx
Labels: Version: Trivial
