Repository artsy/palette, pull requests merged in 2019-03, with the labels that each got.

#305 [Flex] Make `display` prop responsive
  src/elements/Flex/Flex.tsx
Labels: Merge On Green, Version: Patch

#306 Add icons
  src/svgs/PowerIcon.tsx
  src/svgs/SettingsIcon.tsx
  src/svgs/SoloIcon.tsx
  src/svgs/index.tsx
Labels: Merge On Green, Version: Patch

#312 Remove duplicate interface declarations
  src/elements/Box/Box.tsx
Labels: Version: Patch, Version: Trivial

#311 [Menu] Add <Menu> component
  src/elements/Menu/Menu.ios.tsx
  src/elements/Menu/Menu.tsx
  src/elements/Menu/index.tsx
  src/elements/index.tsx
  www/content/docs/components/Menu.mdx
  www/src/components/GlobalComponents.jsx
  www/static/admin/config.js
Labels: Version: Minor

#313 Update palette@latest
  www/package.json
  www/yarn.lock
Labels: Merge On Green, Version: Patch

#310 Improve Link API
  src/elements/Link/Link.tsx
  www/content/docs/elements/buttons/Link.mdx
Labels: Version: Minor

#309 Bar chart
  src/elements/BarChart/Bar.tsx
  src/elements/BarChart/BarChart.test.tsx
  src/elements/BarChart/BarChart.tsx
  src/elements/BarChart/BarLabel.tsx
  src/elements/BarChart/MousePositionContext.tsx
  src/elements/BarChart/index.tsx
  src/elements/index.tsx
  www/content/docs/elements/data-visualization/BarChart.mdx
  www/content/docs/elements/data-visualization/index.mdx
  www/gatsby-node.js
  www/static/admin/config.js
Labels: Jira Synced, Version: Patch

#314 [Link] Make underlineBehavior optional
  src/elements/Link/Link.tsx
Labels: Version: Patch

#315 Make underlineBehavior simpler for consumers
  src/elements/Link/Link.tsx
  src/helpers/injectGlobalStyles.tsx
  www/content/docs/elements/buttons/Link.mdx
Labels: Version: Patch

#318 [Menu] Fix responsive props
  src/elements/Menu/Menu.tsx
Labels: Version: Patch

#319 [Menu] Add onClick handler
  src/elements/Menu/Menu.tsx
  www/content/docs/components/Menu.mdx
Labels: Version: Patch

#317 Add prettier check
  package.json
  src/elements/BarChart/MousePositionContext.tsx
  src/elements/Typography/determineFontSizes.ts
  yarn.lock
Labels: Version: Patch

#322 [Icons] Add `Icon` to icon name
  src/svgs/PageViewsIcon.tsx
  src/svgs/index.tsx
Labels: Version: Patch

#323 [Lib] Bump palette in docs
  www/package.json
  www/yarn.lock
Labels: Version: Trivial

#321 [Tooltip] Add option to have component as tooltip content
  src/elements/Tooltip/Tooltip.tsx
  www/content/docs/elements/inputs/Tooltip.mdx
Labels: Version: Patch

#325 bump version of palette in docs
  www/package.json
  www/yarn.lock
Labels: Version: Trivial

#320 [Lib] Upgrade deps via upgrade-interactive
  src/elements/Tabs/Tabs.tsx
  src/elements/Tabs/__tests__/Tabs.test.tsx
  src/index.tsx
  yarn.lock
Labels: Version: Patch

#328 [ci setup] Use lerna for releases
  lerna.json
  package.json
  packages/palette/package.json
  packages/palette/scripts/clean-up-after-auto.js
  yarn.lock
Labels: Merge On Green, Version: Patch

#330 [ci setup] consolidate changelogs
  CHANGELOG.md
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/src/utils/copyChangelog.js
  packages/palette/CHANGELOG.md
Labels: Merge On Green, Version: Trivial

#332 Fix <Toggle> icon size
  packages/palette/src/elements/Toggle/Toggle.tsx
Labels: Version: Patch

#327 Add 'element' property for specifying element type on Typography
  packages/palette-docs/content/docs/tokens/Typography.mdx
  packages/palette/src/elements/Typography/Typography.tsx
Labels: Merge On Green

#335 adds required prop to textarea
  packages/palette-docs/content/docs/elements/inputs/TextArea.mdx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx
Labels: Version: Minor

#333 Add CSS reset for headings (h1-h6) to global styles
  packages/palette/src/helpers/injectGlobalStyles.tsx
Labels: Version: Patch

#334 Create LazyImage component, allow avatar to be lazy
  packages/palette-docs/content/docs/elements/images/Avatar.mdx
  packages/palette-docs/content/docs/elements/images/Image.mdx
  packages/palette/package.json
  packages/palette/src/elements/Avatar/Avatar.ios.tsx
  packages/palette/src/elements/Avatar/Avatar.shared.tsx
  packages/palette/src/elements/Avatar/Avatar.test.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
  packages/palette/src/elements/Image/Image.ios.tsx
  packages/palette/src/elements/Image/Image.shared.tsx
  packages/palette/src/elements/Image/Image.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
  yarn.lock
Labels: Version: Minor

#336 Correct CMS path to admin resources
  packages/palette-docs/static/admin/config.js
  packages/palette-docs/static/admin/config.yml
Labels: Version: Trivial

#337 Go back to auto-release step in orb
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Version: Patch

#338 Ensure lazy-loaded images fill placeholder container
  packages/palette/src/elements/Image/LazyImage.tsx
Labels: Version: Patch

#339 Add Input to palette
  packages/palette-docs/content/docs/elements/inputs/Input.mdx
  packages/palette/package.json
  packages/palette/src/elements/Input/Input.test.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Input/index.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/tokens.json
Labels: Version: Minor

#341 Update Images “Image”
  packages/palette-docs/content/docs/elements/images/Image.mdx
Labels: Docs

#342 [Box] Add minHeight prop
  packages/palette/src/elements/Box/Box.tsx
Labels: Version: Patch

#340 Update Home “process”
  packages/palette-docs/content/docs/home/process.mdx
Labels: Docs

#344 Update Tokens “Icons”
  packages/palette-docs/content/docs/tokens/Icons.mdx
Labels: Docs

#345 Fix web Collapse component
  packages/palette-docs/content/docs/elements/layout/Collapse.mdx
  packages/palette/src/elements/Collapse/Collapse.test.tsx
  packages/palette/src/elements/Collapse/Collapse.tsx
Labels: Jira Synced, Version: Patch

#350 [RadioGroup] Add deselectable option
  packages/palette-docs/content/docs/elements/inputs/RadioGroup.mdx
  packages/palette/src/elements/Radio/Radio.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.tsx
  yarn.lock
Labels: Version: Minor

#351 Fix debounce
  packages/palette/src/elements/Radio/Radio.tsx
Labels: Version: Patch

#352 Add test to RadioGroup
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.tsx
Labels: Version: Patch

#353 Deal with warnings
  packages/palette/src/elements/Avatar/Avatar.ios.tsx
  packages/palette/src/elements/Avatar/Avatar.shared.tsx
  packages/palette/src/elements/Image/Image.ios.tsx
  packages/palette/src/elements/Image/Image.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
  packages/palette/src/elements/LabeledRange/LabeledRange.tsx
  packages/palette/src/elements/Menu/Menu.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
  packages/palette/src/elements/PriceRange/PriceRange.tsx
  packages/palette/src/elements/ProgressBar/ProgressBar.tsx
  packages/palette/src/elements/ProgressBarTimer/ProgressBarTimer.tsx
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  packages/palette/src/elements/Stepper/Stepper.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
  packages/palette/src/elements/Typography/Typography.tsx
  packages/palette/src/svgs/AddCircleFillIcon.tsx
  packages/palette/src/svgs/ArtsyLogoBlackIcon.tsx
  packages/palette/src/svgs/ArtsyMarkBlackIcon.tsx
  packages/palette/src/svgs/CheckCircleFillIcon.tsx
  packages/palette/src/svgs/CheckCircleIcon.tsx
  packages/palette/src/svgs/CloseCircleIcon.tsx
  packages/palette/src/svgs/EstablishedIcon.tsx
  packages/palette/src/svgs/EyeClosedIcon.tsx
  packages/palette/src/svgs/EyeOpenedIcon.tsx
  packages/palette/src/svgs/InstitutionIcon.tsx
  packages/palette/src/svgs/LogoutIcon.tsx
  packages/palette/src/svgs/MapPinIcon.tsx
  packages/palette/src/svgs/PublicationIcon.tsx
  packages/palette/src/svgs/QuestionCircleIcon.tsx
  packages/palette/src/svgs/UserMultiIcon.tsx
  packages/palette/src/svgs/UserSingleIcon.tsx
Labels: Version: Patch

#356 Don't try to debounce if onSelect isn't defined
  packages/palette/src/elements/Radio/Radio.tsx
Labels: Version: Patch

#355 Remove extraneous attributes from Image component
  packages/palette/src/elements/Image/LazyImage.tsx
  packages/palette/src/helpers/withoutStyleProps.tsx
Labels: Merge On Green, Version: Patch

#360 Don't strip width and height props from images
  packages/palette/src/helpers/withoutStyleProps.tsx
Labels: Version: Patch
