Repository artsy/palette, pull requests merged in 2019-11, with the labels that each got.

#610 Adds Tags container animation
  packages/palette/src/elements/Tags/Tags.ios.tsx
  packages/palette/src/elements/Tags/Tags.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#613 want the Box to support minWidth
  packages/palette/src/elements/Box/Box.tsx
Labels: Merge On Green, Version: Patch

#615 Update typescript to 3.7+
  packages/palette-docs/package.json
  packages/palette/package.json
  yarn.lock
Labels: Merge On Green, Version: Trivial
