Repository artsy/palette, pull requests merged in 2019-09, with the labels that each got.

#579 PURCHASE-1473 - Adds hideCloseXButton prop and allow for closing from wrapper
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/Modal/__tests__/Modal.test.tsx
Labels: Jira Synced, Version: Patch

#577 [PageLoader] Add PageLoader component
  packages/palette-docs/content/docs/elements/loaders/PageLoader.mdx
  packages/palette/package.json
  packages/palette/src/elements/PageLoader/PageLoader.ios.tsx
  packages/palette/src/elements/PageLoader/PageLoader.story.tsx
  packages/palette/src/elements/PageLoader/PageLoader.tsx
  packages/palette/src/elements/PageLoader/index.tsx
  packages/palette/src/elements/ProgressBar/ProgressBar.story.tsx
  packages/palette/src/elements/ProgressBar/ProgressBar.tsx
  packages/palette/src/elements/index.tsx
  yarn.lock
Labels: Merge On Green, Version: Minor

#580 [PageLoader] Cleanup
  packages/palette/src/elements/PageLoader/PageLoader.tsx
Labels: Version: Patch

#581 [Modal] - Checks if wrapper is clicked before closing
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/Modal/__tests__/Modal.test.tsx
Labels: Merge On Green, Version: Patch

#582 Improve modal padding
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Version: Patch

#588 Final modal spacing fixes
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Version: Patch

#587 @jonallured => [Button] Export shape of props
  packages/palette/src/elements/Button/Button.tsx
Labels: Version: Patch

#589 Add artsy footer
  README.md
Labels: Version: Trivial

#590 PURCHASE-1492: added BellFillIcon and BellIcon for ios
  packages/palette/src/svgs/BellFillIcon.ios.tsx
  packages/palette/src/svgs/BellIcon.ios.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#591 [PreloadBar] Change to black and fix size #trivial
  packages/palette/src/elements/BarChart/BarChart.story.tsx
  packages/palette/src/elements/CSSGrid/CSSGrid.story.tsx
  packages/palette/src/elements/DonutChart/DonutChart.story.tsx
  packages/palette/src/elements/LineChart/LineChart.story.tsx
  packages/palette/src/elements/Modal/Modal.story.tsx
  packages/palette/src/elements/ProgressBar/ProgressBar.tsx
Labels: Version: Patch

#594 Remove luc as pont person 😭
  README.md
Labels: Version: Trivial

#595 Algolia updates
  packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
  packages/palette-docs/content/docs/elements/data-visualization/DonutChart.mdx
  packages/palette-docs/content/docs/elements/data-visualization/LineChart.mdx
  packages/palette-docs/content/docs/elements/images/Image.mdx
  packages/palette-docs/content/docs/elements/inputs/Checkbox.mdx
  packages/palette-docs/content/docs/elements/inputs/RadioGroup.mdx
  packages/palette-docs/content/docs/elements/inputs/Select.mdx
  packages/palette-docs/content/docs/elements/inputs/SelectSmall.mdx
  packages/palette-docs/content/docs/elements/inputs/Slider.mdx
  packages/palette-docs/content/docs/elements/layout/CSSGrid.mdx
  packages/palette-docs/content/docs/elements/layout/Flex.mdx
  packages/palette-docs/content/docs/elements/layout/Grid.mdx
  packages/palette-docs/content/docs/elements/layout/ReadMore.mdx
  packages/palette-docs/content/docs/home/getting-started.mdx
  packages/palette-docs/content/docs/home/process.mdx
  packages/palette-docs/content/docs/tokens/Color.mdx
  packages/palette-docs/content/docs/tokens/Spacing.mdx
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/package.json
  packages/palette-docs/src/components/GlobalComponents.jsx
  packages/palette-docs/src/layouts/DefaultLayout.tsx
  yarn.lock
Labels: Version: Trivial
