Repository artsy/palette, pull requests merged in 2020-02, with the labels that each got.

#629 [Docs] Add gatsby-plugin-s3 for deploying app to S3 bucket
  package.json
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/package.json
  yarn.lock
Labels: Docs, Version: Trivial

#631 Deploy docs to s3 on master build
  .circleci/config.yml
  package.json
Labels: Version: Trivial

#630 @zephraph => [Package] Update styled-components to v5
  packages/palette-docs/package.json
  packages/palette/package.json
  packages/palette/src/elements/Banner/Banner.test.tsx
  packages/palette/src/elements/BarChart/BarChart.test.tsx
  packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
  yarn.lock
Labels: Version: Major

#634 @damassi => Revert "@zephraph => [Package] Update styled-components to v5"
  packages/palette-docs/package.json
  packages/palette/package.json
  packages/palette/src/elements/Banner/Banner.test.tsx
  packages/palette/src/elements/BarChart/BarChart.test.tsx
  packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
  yarn.lock
Labels: Version: Major

#640 [Spinner] Adds delay prop for visibility
  packages/palette/src/elements/Spinner/Spinner.shared.tsx
  packages/palette/src/elements/Spinner/Spinner.story.tsx
  packages/palette/src/elements/Spinner/Spinner.tsx
Labels: Version: Minor

#641 Small dropdown arrow is misaligned
  packages/palette/src/elements/Select/Select.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#642 Incorporate Algolia-based search
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/plugins/gatsby-plugin-local-algolia-docsearch/gatsby-ssr.js
  packages/palette-docs/plugins/gatsby-plugin-local-algolia-docsearch/index.js
  packages/palette-docs/plugins/gatsby-plugin-local-algolia-docsearch/package.json
  packages/palette-docs/src/components/Sidebar/SearchBox.tsx
  packages/palette-docs/src/components/Sidebar/algolia.css
  packages/palette-docs/src/components/Sidebar/index.tsx
Labels: Version: Patch

#643 Add new context w/ proper permissions to upload to S3
  .circleci/config.yml
Labels: Version: Trivial

#644 Disable acl to bypass requiring the addition of extra permissions
  packages/palette-docs/gatsby-config.js
Labels: Version: Trivial

#645 Re-add acl permissions to avoid publishing private assets
  packages/palette-docs/gatsby-config.js
Labels: Version: Trivial
