Repository artsy/palette, pull requests merged in 2020-04, with the labels that each got.

#662 Add top to flex
  packages/palette/src/elements/Flex/Flex.tsx
Labels: Version: Minor

#663 Allow `Input` to accept refs
  packages/palette/src/elements/Input/Input.tsx
Labels: Version: Minor

#664 [FX-1889] expand menu component to work with new nav DropDownMenu in reaction
  packages/palette/src/elements/Menu/Menu.tsx
Labels: Version: Patch

#665 [Deletion] Remove page loader
  packages/palette/src/elements/PageLoader/PageLoader.ios.tsx
  packages/palette/src/elements/PageLoader/PageLoader.story.tsx
  packages/palette/src/elements/PageLoader/PageLoader.tsx
  packages/palette/src/elements/PageLoader/index.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Major

#668 Removed spacing, changed font for text area
  packages/palette/src/elements/TextArea/TextArea.story.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
Labels: Version: Patch

#670 Style tweaks for text inputs
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.test.tsx
  packages/palette/src/elements/Input/Input.tsx
Labels: Version: Patch

#671 Update menu component style props
  packages/palette/src/elements/Menu/Menu.tsx
Labels: Version: Patch

#672 [Grid] Add maxWidth prop
  packages/palette/src/elements/Grid/Grid.tsx
Labels: Merge On Green, Version: Minor

#673 [FX-1907] make background color darker for legibility with light text colors
  packages/palette/src/elements/Menu/Menu.tsx
Labels: Version: Patch
