Repository artsy/palette, pull requests merged in 2020-06, with the labels that each got.

#706 Update avatar component to use Sans
  packages/palette/src/elements/Avatar/Avatar.shared.tsx
Labels: Version: Minor

#705 Upgrades to styled-system v5
  packages/palette/package.json
  packages/palette/scripts/generate-styles.ts
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/BarChart/Bar.tsx
  packages/palette/src/elements/CSSGrid/CSSGrid.tsx
  packages/palette/src/elements/CleanTag/CleanTag.tsx
  packages/palette/src/elements/CleanTag/__tests__/CleanTag.test.ts
  packages/palette/src/elements/Grid/Grid.tsx
  packages/palette/src/elements/Image/Image.shared.tsx
  packages/palette/src/elements/Image/Image.story.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/ProgressBar/ProgressBar.tsx
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/Typography/Typography.test.tsx
  packages/palette/src/elements/Typography/determineFontSizes.test.ts
  packages/palette/src/elements/Typography/determineFontSizes.ts
  packages/palette/src/helpers/media.ts
  packages/palette/src/helpers/space.ts
  packages/palette/src/svgs/WeChatIcon.tsx
  yarn.lock
Labels: Version: Major, canary

#708 allow customizing border color for BorderBox
  packages/palette-docs/content/docs/elements/layout/BorderBox.mdx
  packages/palette/src/elements/BorderBox/BorderBoxBase.tsx
Labels: Version: Minor

#707 Unifies Box/Flex
  packages/palette/src/elements/Avatar/Avatar.shared.tsx
  packages/palette/src/elements/BarChart/BarChart.tsx
  packages/palette/src/elements/BorderBox/BorderBoxBase.tsx
  packages/palette/src/elements/Box/Box.tsx
  packages/palette/src/elements/Flex/Flex.tsx
  packages/palette/src/elements/Image/Image.story.tsx
  packages/palette/src/elements/Typography/Typography.tsx
Labels: Version: Major, canary

#710 Fixes avatars in React Native
  packages/palette/src/elements/Avatar/Avatar.shared.tsx
Labels: Merge On Green, Version: Patch

#711 BorderBox should support custom padding
  packages/palette-docs/content/docs/elements/layout/BorderBox.mdx
  packages/palette/src/elements/BorderBox/BorderBoxBase.tsx
Labels: Version: Patch

#713 [chore] Minor Storybook updates
  packages/palette/.storybook/config.js
  packages/palette/package.json
  packages/palette/src/elements/Image/Image.story.tsx
  yarn.lock
Labels: Version: Minor

#712 Remove margin on Toggle component
  packages/palette/src/elements/Toggle/Toggle.tsx
Labels: Version: Minor, canary

#715 Disables knobs to remove dependency on emotion typings
  packages/palette/.storybook/addons.js
  packages/palette/package.json
  packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#714 [web] Implements new typographic styles
  packages/palette/.storybook/preview-head.html
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/Text/Text.ios.tsx
  packages/palette/src/elements/Text/Text.shared.tsx
  packages/palette/src/elements/Text/Text.story.tsx
  packages/palette/src/elements/Text/Text.tsx
  packages/palette/src/elements/Text/index.ts
  packages/palette/src/elements/Text/tokens.ios.ts
  packages/palette/src/elements/Text/tokens.shared.ts
  packages/palette/src/elements/Text/tokens.ts
  packages/palette/src/elements/Typography/Typography.test.tsx
  packages/palette/src/elements/Typography/Typography.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Minor, canary

#717 Add cards from viewing rooms
  packages/palette-docs/content/docs/elements/layout/Cards.mdx
  packages/palette/package.json
  packages/palette/src/elements/Avatar/Avatar.ios.tsx
  packages/palette/src/elements/Cards/CardTag.ios.tsx
  packages/palette/src/elements/Cards/CardTag.shared.tsx
  packages/palette/src/elements/Cards/CardTag.tsx
  packages/palette/src/elements/Cards/Cards.story.tsx
  packages/palette/src/elements/Cards/LargeCard.ios.tsx
  packages/palette/src/elements/Cards/LargeCard.shared.tsx
  packages/palette/src/elements/Cards/LargeCard.tsx
  packages/palette/src/elements/Cards/MediumCard.ios.tsx
  packages/palette/src/elements/Cards/MediumCard.shared.tsx
  packages/palette/src/elements/Cards/MediumCard.tsx
  packages/palette/src/elements/Cards/SmallCard.ios.tsx
  packages/palette/src/elements/Cards/SmallCard.shared.tsx
  packages/palette/src/elements/Cards/SmallCard.tsx
  packages/palette/src/elements/Cards/index.tsx
  packages/palette/src/elements/Modal/ModalBase.story.tsx
  packages/palette/src/elements/index.tsx
  yarn.lock
Labels: Version: Minor

#718 Bumps react-lazy-load-image-component
  packages/palette/package.json
  yarn.lock
Labels: Merge On Green, Version: Patch, canary

#719 [FX-2067] Implements Text.ios
  packages/palette/package.json
  packages/palette/src/elements/Text/Text.ios.tsx
  packages/palette/src/elements/Text/Text.shared.tsx
  packages/palette/src/elements/Text/Text.story.tsx
  packages/palette/src/elements/Text/__tests__/Text.ios.test.tsx
  packages/palette/src/elements/Text/tokens.ios.ts
Labels: Version: Minor
