Repository artsy/palette, pull requests merged in 2020-09, with the labels that each got.

#765 Move paginateCarousel Rename to Original File
  packages/palette/src/elements/Carousel/Carousel.tsx
  packages/palette/src/elements/Carousel/__tests__/Carousel.test.tsx
  packages/palette/src/elements/Carousel/__tests__/paginate.test.ts
  packages/palette/src/elements/Carousel/index.ts
  packages/palette/src/elements/Carousel/paginate.ts
Labels: Merge On Green, Version: Minor

#777 Add 1.5 and 5 to our spacing units
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Cards/MediumCard.tsx
Labels: Merge On Green, Version: Minor

#776 Cleans up Cards; support all image attributes
  packages/palette-docs/content/docs/elements/layout/Cards.mdx
  packages/palette/src/elements/Cards/CardTag.tsx
  packages/palette/src/elements/Cards/Cards.story.tsx
  packages/palette/src/elements/Cards/LargeCard.tsx
  packages/palette/src/elements/Cards/MediumCard.tsx
  packages/palette/src/elements/Cards/SmallCard.tsx
  packages/palette/src/elements/Cards/index.tsx
Labels: Version: Minor

#778 Exposes text variants under theme
  packages/palette/src/Theme.tsx
Labels: Version: Minor

#781 Update gatsby plugins to be node v12 compatible
  .vscode/settings.json
  packages/palette-docs/package.json
  packages/palette/src/elements/Banner/Banner.tsx
  yarn.lock
Labels: Version: Trivial

#783 Fixes horizontal margin overrides
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/elements/Swiper/Swiper.tsx
Labels: Merge On Green, Version: Patch

#784 Add receipt and pending icon
  packages/palette/src/svgs/PendingCircleIcon.tsx
  packages/palette/src/svgs/ReceiptIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#785 Sets default Text variant to `"text"`
  packages/palette/src/elements/Text/Text.tsx
Labels: Merge On Green, Version: Minor

#782 [FX-2245] ReadMore styling
  packages/palette/src/elements/Clickable/Clickable.tsx
  packages/palette/src/elements/HTML/HTML.story.tsx
  packages/palette/src/elements/HTML/HTML.tsx
  packages/palette/src/elements/ReadMore/ReadMore.story.tsx
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx
Labels: Version: Minor, canary

#786 Removed white background from XCircleIcon
  packages/palette/src/svgs/XCircleIcon.tsx
Labels: Merge On Green, Version: Patch

#787 Removes primitives indirection
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
  packages/palette/src/elements/BorderBox/BorderBox.tsx
  packages/palette/src/elements/BorderBox/BorderBoxBase.tsx
  packages/palette/src/elements/Box/Box.tsx
  packages/palette/src/elements/Carousel/Carousel.story.tsx
  packages/palette/src/elements/CleanTag/CleanTag.tsx
  packages/palette/src/elements/Flex/Flex.tsx
  packages/palette/src/elements/Image/Image.tsx
  packages/palette/src/elements/Message/Message.tsx
  packages/palette/src/elements/Separator/Separator.tsx
  packages/palette/src/elements/StackableBorderBox/StackableBorderBox.tsx
  packages/palette/src/elements/Tags/Tags.tsx
  packages/palette/src/elements/Typography/Typography.tsx
  packages/palette/src/platform/primitives.ts
Labels: Version: Trivial, canary

#788 Ensures consistent typography in EntityHeaders
  packages/palette-docs/content/docs/components/EntityHeader.mdx
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
Labels: Version: Patch

#789 Only calls onChange when the active index actually changes
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/Swiper/Swiper.tsx
Labels: Merge On Green, Version: Patch
