Repository artsy/palette, pull requests merged in 2020-10, with the labels that each got.

#790 Converts ReadMore class component to functional component
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx
Labels: Version: Patch, canary

#791 [FX-2317] Fixes pagination arrow alignment
  packages/palette/src/elements/Pagination/Pagination.story.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
Labels: Merge On Green, Version: Patch

#793 style(FX-2320): Remove XS horizontal padding within tabs container
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Jira Synced, Squash On Green, Version: Minor

#794 Implements GridColumns
  packages/palette/src/elements/Cards/Cards.story.tsx
  packages/palette/src/elements/GridColumns/GridColumns.story.tsx
  packages/palette/src/elements/GridColumns/GridColumns.tsx
  packages/palette/src/elements/GridColumns/__tests__/calculateGridColumn.test.ts
  packages/palette/src/elements/GridColumns/calculateGridColumn.tsx
  packages/palette/src/elements/GridColumns/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor, canary

#795 GridColumns typing
  packages/palette/src/elements/GridColumns/GridColumns.tsx
Labels: Version: Patch, canary

#796 feat: add drag icon to icon library
  packages/palette/src/svgs/DragIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#799 [PCI-3] Supports props based navigation in Swiper/Carousel
  packages/palette/package.json
  packages/palette/src/elements/Carousel/Carousel.story.tsx
  packages/palette/src/elements/Carousel/Carousel.tsx
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/elements/Swiper/Swiper.tsx
  packages/palette/src/elements/Swiper/__tests__/activeIndex.test.ts
  packages/palette/src/elements/Swiper/activeIndex.ts
  packages/palette/src/elements/Swiper/percentage.ts
  yarn.lock
Labels: Version: Minor

#802 feat: [Icons] Add TriangleDownIcon
  packages/palette/src/svgs/TriangleDownIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Merge On Green, Version: Minor

#803 fix: All icon to be filled
  packages/palette/src/svgs/TriangleDownIcon.tsx
Labels: Merge On Green, Version: Minor

#804 docs: Add GridColumn docs
  .vscode/settings.json
  packages/palette-docs/content/docs/elements/layout/GridColumn.mdx
Labels: Version: Minor

#806 Updates GridColumns documentation
  packages/palette-docs/content/docs/elements/layout/GridColumns.mdx
Labels: Merge On Green, Version: Trivial

#807 feat: Add blue100 color
  packages/palette/src/Theme.tsx
  packages/palette/src/svgs/TriangleDownIcon.tsx
Labels: Merge On Green, Version: Minor

#809 Includes documentation on how to create a responsive image
  packages/palette-docs/content/docs/elements/images/Image.mdx
  packages/palette/src/elements/Image/Image.tsx
Labels: Version: Minor
