Repository artsy/palette, pull requests merged in 2020-07, with the labels that each got.

#721 Add new BriefcaseIcon to palette system
  packages/palette/src/svgs/BriefcaseIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#722 Supports a small entity header design via "smallVariant" prop
  packages/palette-docs/content/docs/components/EntityHeader.mdx
  packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
Labels: Merge On Green, Version: Minor

#724 Removes blanket focus disable
  packages/palette/src/helpers/injectGlobalStyles.tsx
Labels: Version: Patch

#725 Removes theme from config
  packages/palette/.storybook/config.js
Labels: Merge On Green, Version: Patch

#723 [Part of GALL-2970] - adding a small card to web view
  packages/palette-docs/content/docs/elements/layout/Cards.mdx
  packages/palette/src/elements/Cards/CardTag.shared.tsx
  packages/palette/src/elements/Cards/CardTag.tsx
  packages/palette/src/elements/Cards/SmallCard.ios.tsx
  packages/palette/src/elements/Cards/SmallCard.tsx
Labels: Merge On Green, Version: Minor

#727 [chore] Prevents Chromatic spec diffs
  packages/palette/src/elements/BarChart/BarChart.story.tsx
  packages/palette/src/elements/Cards/Cards.story.tsx
Labels: Merge On Green, Version: Trivial

#729 Upping the diffThreshold a bit more for BarChart
  packages/palette/src/elements/BarChart/BarChart.story.tsx
Labels: Version: Trivial

#728 addinging some grammer :p
  packages/palette-docs/content/docs/elements/layout/Flex.mdx
Labels: Version: Minor

#716 Upgrades styled-bootstrap-grid; removes overflow: hidden
  packages/palette/package.json
  packages/palette/src/elements/Grid/Grid.tsx
  yarn.lock
Labels: Version: Patch, canary

#731 GALL-2970 Add web version of medium card
  packages/palette-docs/content/docs/elements/layout/Cards.mdx
  packages/palette/src/elements/Cards/MediumCard.tsx
Labels: Version: Minor

#734 Removes serif from Text
  packages/palette-docs/content/docs/tokens/Typography.mdx
  packages/palette/src/elements/Text/Text.story.tsx
  packages/palette/src/elements/Text/Text.tsx
  packages/palette/src/elements/Text/tokens.ts
Labels: Merge On Green, Version: Minor

#736 Text extends Box
  packages/palette/src/elements/LabeledRange/LabeledRange.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/elements/Text/Text.tsx
  packages/palette/src/elements/Toggle/Toggle.tsx
  packages/palette/src/svgs/Icon.tsx
  yarn.lock
Labels: Version: Minor

#737 Implements utility for breaking apart layout props
  packages/palette/src/elements/Box/Box.tsx
  packages/palette/src/elements/Box/__tests__/Box.test.tsx
Labels: Version: Minor

#739 [palette-docs] Fixes mysterious error
  packages/palette-docs/content/docs/tokens/Typography.mdx
Labels: Version: Minor

#740 Improves Typography documentation
  packages/palette-docs/content/docs/home/getting-started.mdx
  packages/palette-docs/content/docs/tokens/Typography.mdx
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/src/components/GlobalComponents.jsx
  packages/palette-docs/src/components/Table.tsx
  packages/palette-docs/src/components/TextSpecification.tsx
  packages/palette-docs/src/layouts/DefaultLayout.tsx
Labels: Merge On Green, Version: Trivial

#742 Update Typography docs
  packages/palette-docs/content/docs/tokens/Typography.mdx
Labels: Merge On Green, Version: Trivial

#741 Implements Skeleton
  packages/palette-docs/content/docs/elements/loaders/Skeleton.mdx
  packages/palette/src/elements/Box/Box.tsx
  packages/palette/src/elements/Skeleton/Skeleton.story.tsx
  packages/palette/src/elements/Skeleton/Skeleton.tsx
  packages/palette/src/elements/Skeleton/index.ts
  packages/palette/src/elements/Text/Text.ios.tsx
  packages/palette/src/elements/Text/Text.shared.tsx
  packages/palette/src/elements/Text/Text.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/utils/splitProps.ts
Labels: Merge On Green, Version: Minor, canary

#744 Removes shadow on iOS
  packages/palette/src/elements/Input/Input.tsx
Labels: Merge On Green, Version: Patch

#746 [Docs] Remove WIP from SelectSmall
  packages/palette-docs/content/docs/elements/inputs/SelectSmall.mdx
Labels: Merge On Green, Version: Minor

#747 Implements ResponsiveBox
  packages/palette/package.json
  packages/palette/src/elements/ResponsiveBox/ResponsiveBox.story.tsx
  packages/palette/src/elements/ResponsiveBox/ResponsiveBox.tsx
  packages/palette/src/elements/ResponsiveBox/index.ts
  packages/palette/src/elements/index.tsx
  yarn.lock
Labels: Version: Minor
