Repository artsy/palette, pull requests merged in 2020-05, with the labels that each got.

#678 Updates Palette to use new Eigen repo structure
  README.md
  packages/palette/package.json
Labels: Version: Patch

#679 [ProgressBar] Make transition customizable
  packages/palette/package.json
  packages/palette/src/elements/ProgressBar/ProgressBar.tsx
Labels: Version: Patch

#681 Mixes in missing flex-related functions
  packages/palette/src/elements/Flex/Flex.tsx
Labels: Version: Patch

#680 Remove Modal `forcedScroll` prop / Default `overflow` to `auto`
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Version: Major

#683 [Modal] Do not fire external `onClose` callback on first render
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Version: Patch

#684 [COM-16] - add unstable_trackIn as a prop to Sans and Serif
  packages/palette-docs/content/docs/tokens/Typography.mdx
  packages/palette/src/elements/Typography/Typography.test.tsx
  packages/palette/src/elements/Typography/Typography.tsx
Labels: Version: Minor

#686 Update the Banner component to work well with a content that takes more space
  packages/palette-docs/content/docs/elements/dialogs/Banner.mdx
  packages/palette/src/elements/Banner/Banner.tsx
Labels: Version: Minor

#685 No unstable_trackIn in eigen
  packages/palette/src/elements/Typography/Typography.tsx
Labels: Version: Patch

#687 [CSGN-203] Add PaymentIcon
  packages/palette/src/svgs/PaymentIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#688 Export BorderBoxProps in top-level package
  packages/palette/src/elements/BorderBox/index.tsx
Labels: Version: Minor

#690 Adds HTML component
  packages/palette-docs/content/docs/components/Html.mdx
  packages/palette-docs/src/utils/playgroundHastPlugin.js
  packages/palette/src/elements/HTML/HTML.story.tsx
  packages/palette/src/elements/HTML/HTML.tsx
  packages/palette/src/elements/HTML/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor

#691 Adds HTML.ios.tsx
  packages/palette/src/elements/HTML/HTML.ios.tsx
Labels: Merge On Green, Version: Minor

#689 Add disabledtext to radiogroup
  packages/palette-docs/content/docs/elements/inputs/RadioGroup.mdx
  packages/palette/.storybook/addons.js
  packages/palette/package.json
  packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.tsx
  yarn.lock
Labels: Version: Minor

#692 Use Sans Instead of Serif in EntityHeader component
  packages/palette/src/elements/EntityHeader/EntityHeader.ios.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
Labels: Merge On Green, Version: Minor

#694 Adjusts Chromatic settings
  packages/palette/src/elements/BarChart/BarChart.story.tsx
  packages/palette/src/elements/Dialog/Dialog.story.tsx
  packages/palette/src/elements/DonutChart/DonutChart.story.tsx
  packages/palette/src/elements/LineChart/LineChart.story.tsx
  packages/palette/src/elements/Modal/Modal.story.tsx
Labels: Version: Trivial

#697 Fixes mixed-in classnames coming from styled-components
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/Button.test.tsx
  packages/palette/src/elements/Button/Button.tsx
Labels: Merge On Green, Version: Patch

#693 [FX-1936] Implements ModalBase (take II)
  packages/palette/jest.config.ts
  packages/palette/package.json
  packages/palette/src/elements/BarChart/BarChart.story.tsx
  packages/palette/src/elements/Modal/ModalBase.ios.tsx
  packages/palette/src/elements/Modal/ModalBase.story.tsx
  packages/palette/src/elements/Modal/ModalBase.tsx
  packages/palette/src/elements/Modal/__tests__/ModalBase.test.tsx
  packages/palette/src/elements/Modal/index.tsx
  yarn.lock
Labels: Version: Minor, canary

#700 Update Modal to use Sans title
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Version: Minor

#702 adding `endash` and a `range` helper
  packages/palette-docs/content/docs/elements/data-visualization/BarChart.mdx
  packages/palette-docs/content/docs/elements/inputs/Slider.mdx
  packages/palette-docs/content/docs/tokens/Typography.mdx
  packages/palette/src/elements/Typography/Typography.test.tsx
  packages/palette/src/elements/Typography/Typography.tsx
  packages/palette/src/helpers/index.ts
  packages/palette/src/helpers/typography.ts
Labels: Version: Minor

#703 Clickable
  packages/palette-docs/content/docs/components/Clickable.mdx
  packages/palette/src/elements/Box/Box.tsx
  packages/palette/src/elements/Clickable/Clickable.ios.tsx
  packages/palette/src/elements/Clickable/Clickable.story.tsx
  packages/palette/src/elements/Clickable/Clickable.tsx
  packages/palette/src/elements/Clickable/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor
