Repository artsy/palette, pull requests merged in 2020-01, with the labels that each got.

#624 Upgrade `react-lazy-load-image-component` off of beta
  packages/palette/package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#625 [MX-144] Updates Settings icon #trivial
  packages/palette/src/svgs/SettingsIcon.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#627 [MX-137] Add XCircleIcon
  packages/palette/src/svgs/XCircleIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Patch

#628 Fix lazy load double download issue by updating lib
  packages/palette/package.json
  yarn.lock
Labels: Merge On Green, Version: Patch
