Repository artsy/palette, pull requests merged in 2020-08, with the labels that each got.

#751 Reverts serif removal, migrates HTML to new typography
  packages/palette/src/elements/HTML/HTML.story.tsx
  packages/palette/src/elements/HTML/HTML.tsx
  packages/palette/src/elements/Text/Text.story.tsx
  packages/palette/src/elements/Text/tokens.ts
Labels: Merge On Green, Version: Major

#752 Adds remaining block-level elements that can come from rendered Markdown
  packages/palette/src/elements/HTML/HTML.story.tsx
  packages/palette/src/elements/HTML/HTML.tsx
Labels: Merge On Green, Version: Patch

#755 Removes lodash
  packages/palette/.babelrc
  packages/palette/package.json
  packages/palette/src/elements/BarChart/BarChart.tsx
  packages/palette/src/elements/LineChart/LineChartSVG.tsx
  packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
  packages/palette/src/elements/ProgressBarTimer/ProgressBarTimer.tsx
  packages/palette/src/elements/Radio/Radio.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/elements/ReadMore/ReadMore.story.tsx
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/svgs/_icons.story.tsx
  yarn.lock
Labels: Version: Patch

#757 Updates avatar size and typography for entity header small variant
  packages/palette-docs/content/docs/components/EntityHeader.mdx
  packages/palette/src/elements/Avatar/Avatar.shared.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
Labels: Version: Minor

#759 Chore - Cleanup Dependency Cycles
  packages/palette/src/elements/LabeledRange/LabeledRange.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
  packages/palette/src/elements/PriceRange/PriceRange.tsx
  packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  packages/palette/src/elements/Stepper/Stepper.tsx
  packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
  packages/palette/src/elements/Toggle/Toggle.tsx
Labels: Version: Minor

#760 [FX-2175] Carousel
  packages/palette/src/elements/Carousel/Carousel.ios.tsx
  packages/palette/src/elements/Carousel/Carousel.story.tsx
  packages/palette/src/elements/Carousel/Carousel.tsx
  packages/palette/src/elements/Carousel/__tests__/Carousel.test.tsx
  packages/palette/src/elements/Carousel/__tests__/paginate.test.ts
  packages/palette/src/elements/Carousel/index.ts
  packages/palette/src/elements/Carousel/paginate.ts
  packages/palette/src/elements/Skip/Skip.story.tsx
  packages/palette/src/elements/Skip/Skip.tsx
  packages/palette/src/elements/Skip/index.ts
  packages/palette/src/elements/VisuallyHidden/VisuallyHidden.tsx
  packages/palette/src/elements/VisuallyHidden/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor, canary

#761 [FX-2175] Swiper, ProgressDots, custom navigation Carousel buttons
  packages/palette/src/elements/Carousel/Carousel.story.tsx
  packages/palette/src/elements/Carousel/Carousel.tsx
  packages/palette/src/elements/Carousel/CarouselNavigation.tsx
  packages/palette/src/elements/Carousel/__tests__/Carousel.test.tsx
  packages/palette/src/elements/Carousel/index.ts
  packages/palette/src/elements/ProgressDots/ProgressDots.story.tsx
  packages/palette/src/elements/ProgressDots/ProgressDots.tsx
  packages/palette/src/elements/ProgressDots/__tests__/ProgressDots.test.tsx
  packages/palette/src/elements/ProgressDots/index.ts
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/elements/Swiper/Swiper.tsx
  packages/palette/src/elements/Swiper/__tests__/Swiper.test.tsx
  packages/palette/src/elements/Swiper/__tests__/activeIndex.test.ts
  packages/palette/src/elements/Swiper/__tests__/percentage.test.ts
  packages/palette/src/elements/Swiper/activeIndex.ts
  packages/palette/src/elements/Swiper/index.ts
  packages/palette/src/elements/Swiper/percentage.ts
  packages/palette/src/elements/index.tsx
  packages/palette/src/utils/useUpdateEffect.ts
Labels: Version: Minor, canary

#762 Updates carousel arrow sizing and color
  packages/palette/src/elements/Carousel/Carousel.tsx
  packages/palette/src/elements/Carousel/CarouselNavigation.tsx
Labels: Merge On Green, Version: Patch

#763 Pass through done prop on SkeletonText
  packages/palette/src/elements/Skeleton/Skeleton.story.tsx
  packages/palette/src/elements/Skeleton/Skeleton.tsx
Labels: Merge On Green, Version: Patch

#764 Adds support for `srcSet`
  packages/palette/src/elements/Image/Image.shared.tsx
  packages/palette/src/elements/Image/Image.story.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
Labels: Merge On Green, Version: Patch
