Repository artsy/palette, pull requests merged in 2020-03, with the labels that each got.

#647 [Spinner] Remove fade
  packages/palette/src/elements/Spinner/Spinner.tsx
Labels: Merge On Green, Version: Patch

#649 Move docsearch CSS to beginning of head so that our custom styles override it
  packages/palette-docs/plugins/gatsby-plugin-local-algolia-docsearch/gatsby-ssr.js
Labels: Version: Patch

#650 Update update
  packages/palette-docs/src/components/Sidebar/index.tsx
Labels: Version: Patch

#651 Add code snippets to <Banner> docs
  packages/palette-docs/content/docs/elements/dialogs/Banner.mdx
Labels: Docs, Merge On Green

#652 Added no artwork icon
  packages/palette/src/svgs/NoArtworkIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Jira Synced, Merge On Green, Version: Minor

#653 Add name prop to TextArea
  packages/palette-docs/content/docs/elements/inputs/TextArea.mdx
  packages/palette/src/elements/TextArea/TextArea.story.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx
Labels: Version: Minor

#654 Add the ability to have a secondary action on the toggle
  packages/palette/src/elements/Toggle/Toggle.story.tsx
  packages/palette/src/elements/Toggle/Toggle.tsx
Labels: Version: Minor

#655 Use a stable image for CSSGrid story.
  packages/palette/src/elements/CSSGrid/CSSGrid.story.tsx
Labels: Merge On Green, Version: Trivial

#656 changed casing of fillRule and clipRule for no artwork icon
  packages/palette/src/svgs/NoArtworkIcon.tsx
Labels: Version: Patch

#657 Adjust left/right padding on small buttons for mWeb (to match iOS styling)
  packages/palette/src/elements/Button/Button.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#658 Allow the Artsy logo to be scaled
  packages/palette/src/svgs/ArtsyLogoBlackIcon.tsx
Labels: Version: Minor

#659 Add missing `flexShrink` to Flex component
  packages/palette/src/elements/Flex/Flex.tsx
Labels: Merge On Green, Version: Patch

#660 Add fallback image support to avatar
  packages/palette-docs/content/docs/elements/images/Avatar.mdx
  packages/palette/package.json
  packages/palette/src/elements/Avatar/Avatar.test.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
  packages/palette/src/elements/Flex/Flex.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
  yarn.lock
Labels: Merge On Green, Version: Minor
