Repository artsy/palette, pull requests merged in 2020-11, with the labels that each got.

#810 feat: support boolean errors for Input
  packages/palette/src/elements/Input/Input.test.tsx
  packages/palette/src/elements/Input/Input.tsx
Labels: Version: Minor

#812 trivial: add target to MenuItem
  packages/palette/src/elements/Menu/Menu.tsx
Labels: Version: Minor, canary

#813 Add new icons for /consign2
  packages/palette/src/svgs/AddItemIcon.tsx
  packages/palette/src/svgs/ArtworkWithBadgeIcon.tsx
  packages/palette/src/svgs/ArtworkWithCheckIcon.tsx
  packages/palette/src/svgs/LightningBoltIcon.tsx
  packages/palette/src/svgs/MultipleOffersIcon.tsx
  packages/palette/src/svgs/UserWithChartIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#814 fix: [Text] update variant type to support array syntax
  packages/palette/src/elements/Text/tokens.ts
Labels: Merge On Green, Version: Minor

#815 fix: Fix type def
  packages/palette/src/elements/Text/Text.tsx
  packages/palette/src/elements/Text/tokens.ts
Labels: Version: Minor

#816 fix: Use ResponsiveValue helper
  packages/palette/src/elements/Text/Text.tsx
Labels: Version: Minor

#817 Extract palette tokens into a separate package
  lerna.json
  package.json
  packages/palette-tokens/README.md
  packages/palette-tokens/package.json
  packages/palette-tokens/src/index.ts
  packages/palette-tokens/src/text.ts
  packages/palette-tokens/tsconfig.json
Labels: Version: Major

#819 feat: update colors
  packages/palette-docs/content/docs/tokens/Color.mdx
  packages/palette-tokens/src/index.ts
  packages/palette/src/Theme.tsx
Labels: Merge On Green, Version: Minor

#820 feat: update message component
  packages/palette-docs/content/docs/elements/dialogs/Message.mdx
  packages/palette/src/elements/Message/Message.tsx
Labels: Version: Minor
