Repository artsy/palette, pull requests merged in 2020-12, with the labels that each got.

#822 refactor: Reorganize pagination and improve tests
  packages/palette/src/elements/Pagination/LargePagination.tsx
  packages/palette/src/elements/Pagination/Pagination.story.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
  packages/palette/src/elements/Pagination/SmallPagination.tsx
  packages/palette/src/elements/Pagination/__tests__/LargePagination.test.tsx
  packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
  packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx
  packages/palette/src/elements/Pagination/index.tsx
Labels: Version: Trivial

#825 feature: Development Dependencies
  packages/palette-docs/package.json
  packages/palette/package.json
  yarn.lock
Labels: Version: Patch, canary

#821 feat: implements base tabs
  packages/palette/src/elements/BaseTabs/BaseTab.story.tsx
  packages/palette/src/elements/BaseTabs/BaseTab.tsx
  packages/palette/src/elements/BaseTabs/BaseTabs.tsx
  packages/palette/src/elements/BaseTabs/index.ts
  packages/palette/src/elements/Stepper/Stepper.story.tsx
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Minor, canary

#829 fix(tabs): converts back to anys
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Merge On Green, Version: Patch

#830 fix(basetabs): support nested fragments
  packages/palette/src/elements/BaseTabs/BaseTab.story.tsx
  packages/palette/src/elements/BaseTabs/BaseTabs.tsx
  packages/palette/src/helpers/__tests__/flattenChildren.test.tsx
  packages/palette/src/helpers/flattenChildren.ts
Labels: Merge On Green, Version: Minor

#831 fix(swiper): inlines default margins to simplify setting alternatives
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/elements/Swiper/Swiper.tsx
Labels: Merge On Green, Version: Patch

#832 fix(skeleton): implements appropriate scaling for multiline texts
  packages/palette/src/elements/Skeleton/Skeleton.story.tsx
  packages/palette/src/elements/Skeleton/Skeleton.tsx
Labels: Version: Patch

#833 feat: add circle fill icon
  packages/palette/src/svgs/AlertCircleFillIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Patch
