Repository artsy/palette, pull requests merged in 2021-10, with the labels that each got.

#1049 fix(horizontaloverflow): ensures internal heights match external
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.story.tsx
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.tsx
Labels: Version: Patch

#1051 feat(tabs): supports autoscrolling on tab selection
  packages/palette/src/elements/BaseTabs/BaseTab.tsx
  packages/palette/src/elements/Stepper/Stepper.tsx
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Version: Minor

#1053 [breaking change] feat(cards): migrates to v3
  packages/palette/src/elements/Cards/Card/Card.tsx
  packages/palette/src/elements/Cards/Card/v2.tsx
  packages/palette/src/elements/Cards/Card/v3.tsx
  packages/palette/src/elements/Cards/CardTag.tsx
  packages/palette/src/elements/Cards/Cards.story.tsx
  packages/palette/src/elements/Cards/TriptychCard/TriptychCard.tsx
  packages/palette/src/elements/Cards/TriptychCard/v2.tsx
  packages/palette/src/elements/Cards/TriptychCard/v3.tsx
  packages/palette/src/elements/Cards/index.tsx
  packages/palette/src/helpers/shadow.ts
Labels: Version: Major, canary

#1055 docs(types): Improve DX on Button/Text variants
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Text/Text.tsx
Labels: Version: Minor

#1057 fix(labeledinput): fixes height when title/description are present
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.tsx
Labels: Version: Patch

#1060 feat: implements toasts
  packages/palette/src/elements/Toasts/Toast.story.tsx
  packages/palette/src/elements/Toasts/Toast.tsx
  packages/palette/src/elements/Toasts/Toasts.story.tsx
  packages/palette/src/elements/Toasts/Toasts.tsx
  packages/palette/src/elements/Toasts/index.ts
  packages/palette/src/elements/Toasts/useToasts.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Minor, canary

#1062 fix(autocomplete): display options if they are present regardless of query
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Merge On Green, Version: Patch
