Repository artsy/palette, pull requests merged in 2021-01, with the labels that each got.

#824 refactor: Use links for pagination
  .vscode/settings.json
  packages/palette/.babelrc
  packages/palette/package.json
  packages/palette/src/elements/Pagination/LargePagination.tsx
  packages/palette/src/elements/Pagination/SmallPagination.tsx
  packages/palette/src/elements/Pagination/__tests__/LargePagination.test.tsx
  packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx
  yarn.lock
Labels: Version: Minor

#840 feat(pagination): includes page number on next callback
  packages/palette/src/elements/Pagination/LargePagination.tsx
  packages/palette/src/elements/Pagination/Pagination.story.tsx
  packages/palette/src/elements/Pagination/SmallPagination.tsx
  packages/palette/src/elements/Pagination/__tests__/LargePagination.test.tsx
  packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx
Labels: Version: Minor, canary

#841 fix(button): button updates
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/Button.test.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Button/index.ts
  packages/palette/src/elements/Button/tokens.ts
Labels: Version: Minor, canary

#842 fix(button): ensure loading styles take precedence over hover
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/Button.tsx
Labels: Version: Patch

#843 Centralize some of the minor helpers w/ type updates
  packages/palette-tokens/src/helpers.ts
  packages/palette-tokens/src/index.ts
Labels: Version: Minor

#844 Ensure the looser color type definition gets exported
  packages/palette-tokens/src/helpers.ts
Labels: Version: Patch
