Repository artsy/palette, pull requests merged in 2021-06, with the labels that each got.

#939 feat(tooltip): supports v3; supports keyboard focus
  packages/palette/src/elements/Tooltip/Tooltip.story.tsx
  packages/palette/src/elements/Tooltip/Tooltip.tsx
Labels: Version: Minor, canary

#940 add increase/decrease icons
  packages/palette/src/svgs/DecreaseIcon.tsx
  packages/palette/src/svgs/IncreaseIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor, canary

#943 fix: Small card images width
  packages/palette/src/elements/Cards/SmallCard.tsx
Labels: Version: Minor

#944 fix(radio): allows for custom labels to occupy immediate container
  packages/palette/src/elements/Radio/Radio.story.tsx
  packages/palette/src/elements/Radio/Radio.tsx
Labels: Merge On Green, Version: Patch

#946 feat(button): supports `as` prop
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/v2/Button.tsx
  packages/palette/src/elements/Button/v3/Button.tsx
Labels: Version: Minor

#947 Tooltip/Popover positioning
  packages/palette/package.json
  packages/palette/src/elements/BorderBox/BorderBox.tsx
  packages/palette/src/elements/BorderBox/BorderBoxBase.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Button/v2/Button.tsx
  packages/palette/src/elements/Button/v3/Button.tsx
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/elements/Popover/Popover.tsx
  packages/palette/src/elements/Popover/index.ts
  packages/palette/src/elements/Tooltip/Tooltip.story.tsx
  packages/palette/src/elements/Tooltip/Tooltip.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/index.tsx
  packages/palette/src/utils/index.ts
  packages/palette/src/utils/useClickOutside.ts
  packages/palette/src/utils/usePosition.ts
  yarn.lock
Labels: Version: Minor, canary

#948 fix(popover): skips focus management on initial mount
  packages/palette/src/elements/Popover/Popover.tsx
Labels: Merge On Green, Version: Patch

#949 fix(tooltip): avoids blowing away child props
  packages/palette/src/elements/Tooltip/Tooltip.story.tsx
  packages/palette/src/elements/Tooltip/Tooltip.test.tsx
  packages/palette/src/elements/Tooltip/Tooltip.tsx
Labels: Version: Patch

#942 Some small cleanup
  packages/palette-docs/content/docs/tokens/Icons.mdx
  packages/palette/src/svgs/PageViewsIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#950 fix(image,skeleton): optimizes skeleton animations
  packages/palette/src/elements/Image/Image.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
  packages/palette/src/elements/Skeleton/Skeleton.tsx
Labels: Version: Patch, canary

#951 feat(placeholder): implements placeholder
  packages/palette/src/elements/Placeholder/Placeholder.story.tsx
  packages/palette/src/elements/Placeholder/Placeholder.tsx
  packages/palette/src/elements/Placeholder/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor, canary

#953 fix(skeleton): removes placeholder; updates skeleton
  packages/palette/src/elements/Image/Image.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
  packages/palette/src/elements/Placeholder/Placeholder.story.tsx
  packages/palette/src/elements/Placeholder/Placeholder.tsx
  packages/palette/src/elements/Placeholder/index.ts
  packages/palette/src/elements/Skeleton/Skeleton.story.tsx
  packages/palette/src/elements/Skeleton/Skeleton.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Patch, canary

#954 Remove me as point person
  README.md
Labels: Version: Minor

#955 Remove me from renovate.json
  renovate.json
Labels: Version: Minor

#956 fix: Remove react-spring
  packages/palette/package.json
  packages/palette/src/elements/DonutChart/DonutChart.test.tsx
  packages/palette/src/elements/DonutChart/DonutChart.tsx
  packages/palette/src/elements/LineChart/LineChart.test.tsx
  packages/palette/src/elements/LineChart/LineChart.tsx
  packages/palette/src/elements/LineChart/LineChartSVG.tsx
  packages/palette/src/elements/Modal/Modal.tsx
  yarn.lock
Labels: Version: Minor

#959 fix(join): supports nested children
  packages/palette/src/elements/Join/Join.story.tsx
  packages/palette/src/elements/Join/Join.tsx
Labels: Version: Patch

#961 fix(progressdots): supports click
  packages/palette/src/elements/ProgressDots/ProgressDots.story.tsx
  packages/palette/src/elements/ProgressDots/ProgressDots.tsx
  packages/palette/src/elements/ProgressDots/__tests__/ProgressDots.test.tsx
Labels: Merge On Green, Version: Minor

#962 feat(shelf): exports shelf nav buttons; improves feedback
  packages/palette/src/elements/Shelf/Shelf.story.tsx
  packages/palette/src/elements/Shelf/Shelf.tsx
  packages/palette/src/elements/Shelf/ShelfNavigation.tsx
  packages/palette/src/elements/Shelf/index.ts
Labels: Version: Minor

#963 feat(text): adds line-clamp
  packages/palette/src/elements/Text/Text.story.tsx
  packages/palette/src/elements/Text/Text.tsx
Labels: Version: Minor

#964 fix(swiper,carousel): loosens children type
  packages/palette/src/elements/Carousel/Carousel.tsx
  packages/palette/src/elements/Swiper/Swiper.tsx
Labels: Merge On Green, Version: Patch
