Repository artsy/palette, pull requests merged in 2021-07, with the labels that each got.

#965 fix(tabs): attempts to fix unstyled tabs in force
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Version: Patch, canary

#967 fix(tabs): fixes styling
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Version: Patch

#968 chore(chromatic): updates chromatic
  packages/palette/package.json
  yarn.lock
Labels: Version: Minor

#969 fix(PX-4310): get page count information from Swiper and Carousel
  packages/palette/src/elements/Carousel/Carousel.tsx
  packages/palette/src/elements/Carousel/__tests__/Carousel.test.tsx
  packages/palette/src/elements/Swiper/Swiper.tsx
  packages/palette/src/elements/Swiper/__tests__/Swiper.test.tsx
Labels: Version: Minor

#970 fix(useposition): silences uselayouteffect ssr warning
  packages/palette/src/utils/useIsomorphicLayoutEffect.ts
  packages/palette/src/utils/usePosition.ts
Labels: Version: Patch

#974 fix: Fix CI deploys
  .circleci/config.yml
  package.json
  packages/palette/src/elements/Carousel/Carousel.story.tsx
  packages/palette/src/elements/Grid/Grid.story.tsx
  packages/palette/src/elements/GridColumns/GridColumns.story.tsx
  packages/palette/src/elements/Image/Image.story.tsx
  packages/palette/src/elements/Modal/ModalBase.story.tsx
  packages/palette/src/elements/ProgressDots/ProgressDots.tsx
  packages/palette/src/elements/Shelf/Shelf.story.tsx
  packages/palette/src/elements/Skeleton/Skeleton.story.tsx
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/themes/Themes.story.tsx
Labels: Version: Minor

#976 fix(PX-3894): fix end shadow for BaseTabs component
  packages/palette/src/elements/BaseTabs/BaseTabs.tsx
Labels: Version: Patch

#978 fix(image): supports native img props
  packages/palette/src/elements/Image/Image.story.tsx
  packages/palette/src/elements/Image/Image.tsx
Labels: Version: Patch, canary

#979 feat(hooks): exports hooks
  packages/palette/src/utils/index.ts
Labels: Version: Minor

#980 fix: Fix missing TextVariant export
  packages/palette/src/Theme.tsx
Labels: Merge On Green, Version: Patch

#981 fix: storybook compile
  package.json
Labels: Version: Minor

#982 fix: Make sure to compile monorepo packages before publish
  packages/palette/package.json
Labels: Version: Minor

#984 fix(PX-4059): prevent link click if there is no next or prev page
  packages/palette/src/elements/Pagination/SmallPagination.tsx
  packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx
Labels: Version: Patch

#987 feat: Export v2/v3 theme constants
  packages/palette/src/Theme.tsx
Labels: Merge On Green, Version: Minor

#988 feat(textarea): supports v3
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/TextArea/TextArea.story.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx
  packages/palette/src/elements/TextArea/tokens/types.ts
  packages/palette/src/elements/TextArea/tokens/v2.ts
  packages/palette/src/elements/TextArea/tokens/v3.ts
Labels: Version: Minor

#989 fix(textarea): passes default value
  packages/palette/src/elements/TextArea/TextArea.story.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
Labels: Version: Patch

#990 Input/TextArea refinements
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/TextArea/TextArea.story.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/TextArea/tokens/v2.ts
  packages/palette/src/elements/TextArea/tokens/v3.ts
Labels: Version: Patch
