Repository artsy/palette, pull requests merged in 2021-09, with the labels that each got.

#1029 fix(tabs): loosens up tab types so as to support conditional children
  packages/palette/src/elements/BaseTabs/BaseTabs.tsx
  packages/palette/src/elements/Tabs/Tabs.story.tsx
Labels: Merge On Green, Version: Patch

#1030 change modal close to onMouseDown
  packages/palette/src/elements/Modal/ModalBase.tsx
Labels: Version: Patch, Jira Synced

#1032 feat(autocompleteinput): adds loading indicator
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Merge On Green, Version: Minor

#1034 feat: extracts horizontal overflow component from base tabs
  packages/palette/src/elements/BaseTabs/BaseTabs.tsx
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.story.tsx
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.tsx
  packages/palette/src/elements/HorizontalOverflow/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor

#1035 feat(pill): updates pill variants to match current specs
  packages/palette/src/elements/Pill/Pill.tsx
  packages/palette/src/elements/Pill/tokens.ts
Labels: Version: Minor

#1036 feat(ReadMore): Added Read less functionality
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx
Labels: Version: Minor, Jira Synced

#1041 feat(pill): search pill variant
  packages/palette/src/elements/Pill/tokens.ts
Labels: Version: Minor

#1042 fix(button): ensures submit buttons are same font-weight
  packages/palette/src/elements/Button/v2/Button.tsx
  packages/palette/src/elements/Button/v3/Button.tsx
Labels: Merge On Green, Version: Patch

#1043 chore: migrates to eslint
  packages/palette/.eslintrc.js
  packages/palette/package.json
  packages/palette/tslint.json
  yarn.lock
Labels: Version: Trivial, Squash On Green

#1044 fix(modalbase): keeps maxheight in sync
  packages/palette/src/elements/Modal/ModalBase.tsx
Labels: Merge On Green, Version: Patch

#1045 fix(hooks): improves focus lock and mutation observer hooks
  packages/palette-docs/content/docs/hooks/useFocusLock.mdx
  packages/palette/src/utils/useFocusLock.story.tsx
  packages/palette/src/utils/useFocusLock.ts
  packages/palette/src/utils/useMutationObserver.ts
Labels: Version: Patch

#1047 Deprecate <Link>
  packages/palette/src/elements/Link/Link.tsx
Labels: Version: Patch
