Repository artsy/palette, pull requests merged in 2021-05, with the labels that each got.

#917 Shelf component
  packages/palette/src/elements/FullBleed/FullBleed.story.tsx
  packages/palette/src/elements/FullBleed/FullBleed.tsx
  packages/palette/src/elements/FullBleed/index.ts
  packages/palette/src/elements/Shelf/Shelf.story.tsx
  packages/palette/src/elements/Shelf/Shelf.tsx
  packages/palette/src/elements/Shelf/index.ts
  packages/palette/src/elements/Swiper/Swiper.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/helpers/index.ts
  packages/palette/src/helpers/visuallyDisableScrollbar.ts
Labels: Version: Minor

#918 feat: Add alignItems prop to shelf
  packages/palette/src/elements/Shelf/Shelf.tsx
Labels: Version: Minor

#919 feat: Add showProgress prop to Shelf
  packages/palette/src/elements/Shelf/Shelf.story.tsx
  packages/palette/src/elements/Shelf/Shelf.tsx
Labels: Version: Minor

#920 feat: Fix Shelf stories
  packages/palette/src/elements/Shelf/Shelf.story.tsx
Labels: Version: Trivial

#921 fix: Increase scroll bar space
  packages/palette/src/elements/Shelf/Shelf.tsx
Labels: Version: Minor

#922 feat: [Image] add maxHeight props
  packages/palette/src/elements/Image/Image.tsx
Labels: Version: Minor

#923 fix: [Shelf] Dont show arrows if on touch device
  packages/palette/src/elements/Shelf/Shelf.tsx
Labels: Version: Minor

#925 fix(shelf): smoother progress
  packages/palette/src/elements/ProgressBar/ProgressBar.tsx
  packages/palette/src/elements/Shelf/Shelf.tsx
Labels: Version: Patch

#929 [v3] Supports EntityHeader, Avatar
  packages/palette/src/elements/Avatar/Avatar.story.tsx
  packages/palette/src/elements/Avatar/Avatar.test.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
  packages/palette/src/elements/Avatar/tokens.ts
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  packages/palette/src/elements/EntityHeader/v2/EntityHeader.tsx
  packages/palette/src/elements/EntityHeader/v3/EntityHeader.tsx
  packages/palette/src/elements/Spacer/Spacer.tsx
Labels: Version: Minor

#931 Loosen tab types to allow null, undefined
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Merge On Green, Version: Patch

#932 fix(select): vertically centers label
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#933 fix(shelf): improves first page previous button navigation
  packages/palette/src/elements/Shelf/Shelf.tsx
Labels: Version: Minor

#935 feat(shelf): implements custom scrollbar
  packages/palette/src/elements/Shelf/Shelf.story.tsx
  packages/palette/src/elements/Shelf/Shelf.tsx
  packages/palette/src/elements/Shelf/ShelfScrollBar.tsx
  packages/palette/src/elements/Shelf/__tests__/ShelfScrollBar.test.tsx
  packages/palette/src/elements/Shelf/index.ts
  packages/palette/src/elements/Shelf/useClickScroll.ts
  packages/palette/src/elements/Shelf/useDragScroll.ts
Labels: Merge On Green, Version: Minor, canary

#937 fix(shelf): vertically centers arrows relative to rail
  packages/palette/package.json
  packages/palette/src/elements/Shelf/Shelf.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch
