Repository artsy/palette, pull requests merged in 2021-11, with the labels that each got.

#1066 fix(tabs): add scrollIntoView for active tab
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Merge On Green, Version: Minor

#1070 fix(tabs): avoids scrolling on mount
  packages/palette/src/elements/BaseTabs/BaseTabs.tsx
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.tsx
  packages/palette/src/elements/Stepper/Stepper.tsx
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Version: Patch, canary

#1071 feat(button): improves support for icon buttons
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/v3/Button.tsx
  packages/palette/src/helpers/color.ts
  packages/palette/src/svgs/Icon.tsx
Labels: Merge On Green, Version: Minor

#1073 feat(pill): supports pill with icons
  packages/palette-docs/content/docs/elements/Pill.mdx
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
Labels: Merge On Green

#1075 fix(DSWGW-99): Autocomplete Q/A
  packages/palette/package.json
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/utils/index.ts
  packages/palette/src/utils/useContainsFocus.ts
  yarn.lock
Labels: Version: Patch, canary

#1077 fix(autocomplete): improves onclose; fixes memory leak
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
  packages/palette/src/utils/useContainsFocus.ts
Labels: Merge On Green, Version: Patch

#1078 fix(clickable): resets margin for safari
  packages/palette/src/elements/Clickable/Clickable.story.tsx
  packages/palette/src/elements/Clickable/Clickable.tsx
Labels: Merge On Green, Version: Patch

#1076 feat(NX02486): adjusts the modal to the new design
  packages/palette/src/elements/Modal/Modal.story.tsx
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/utils/useOnScroll.ts
Labels: Version: Minor, Jira Synced, canary

#1079 fix(autocomplete): only closes when options are visible
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Merge On Green, Version: Patch
