Repository artsy/palette, pull requests merged in 2021-03, with the labels that each got.

#863 fix(a11y): makes radio / radio groups accessible
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  packages/palette/src/elements/Radio/Radio.story.tsx
  packages/palette/src/elements/Radio/Radio.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.tsx
Labels: Merge On Green, Version: Patch, canary

#866 Revert "fix(a11y): makes radio / radio groups accessible"
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  packages/palette/src/elements/Radio/Radio.story.tsx
  packages/palette/src/elements/Radio/Radio.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.tsx
Labels: Merge On Green, Version: Patch

#868 Pulling over stories from radio button
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  packages/palette/src/elements/Radio/Radio.story.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
Labels: Merge On Green, Version: Trivial

#865 V3 Theme
  packages/palette-docs/content/docs/tokens/Typography.mdx
  packages/palette/.storybook/preview.js
  packages/palette/package.json
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Button/index.ts
  packages/palette/src/elements/Button/tokens.ts
  packages/palette/src/elements/Button/types.ts
  packages/palette/src/elements/Button/v2/Button.tsx
  packages/palette/src/elements/Button/v2/tokens.ts
  packages/palette/src/elements/Button/v3/Button.tsx
  packages/palette/src/elements/Button/v3/tokens.ts
  packages/palette/src/elements/GridColumns/GridColumns.tsx
  packages/palette/src/elements/Modal/__tests__/Modal.test.tsx
  packages/palette/src/elements/Separator/Separator.story.tsx
  packages/palette/src/elements/Separator/Separator.tsx
  packages/palette/src/elements/Spinner/Spinner.tsx
  packages/palette/src/elements/Text/Text.story.tsx
  packages/palette/src/elements/Text/Text.tsx
  packages/palette/src/elements/Text/tokens/index.ts
  packages/palette/src/elements/Text/tokens/types.ts
  packages/palette/src/elements/Text/tokens/v2.ts
  packages/palette/src/elements/Text/tokens/v3.ts
  packages/palette/src/themes/Themes.story.tsx
  packages/palette/src/themes/index.ts
  packages/palette/src/themes/v2.tsx
  packages/palette/src/themes/v3.tsx
  yarn.lock
Labels: Version: Minor, canary

#870 Avoids failing specs on unthemed components
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Button/v2/Button.tsx
  packages/palette/src/elements/Button/v3/Button.tsx
  packages/palette/src/elements/Modal/__tests__/Modal.test.tsx
Labels: Version: Patch

#869 [v3] Banner/Message
  packages/palette/src/elements/Banner/Banner.story.tsx
  packages/palette/src/elements/Banner/Banner.test.tsx
  packages/palette/src/elements/Banner/Banner.tsx
  packages/palette/src/elements/Message/Message.story.tsx
  packages/palette/src/elements/Message/Message.tsx
  packages/palette/src/themes/v2.tsx
  packages/palette/src/themes/v3.tsx
Labels: Version: Major, canary

#872 [v3] Pill
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/v3/Button.tsx
  packages/palette/src/elements/Button/v3/tokens.ts
  packages/palette/src/elements/Carousel/Carousel.story.tsx
  packages/palette/src/elements/Clickable/Clickable.story.tsx
  packages/palette/src/elements/Clickable/Clickable.tsx
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
  packages/palette/src/elements/Pill/index.ts
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/helpers/shadow.ts
  packages/palette/src/themes/Themes.story.tsx
Labels: Version: Minor

#873 feat(breadcrumbs): implements breadcrumbs component
  packages/palette/src/elements/Breadcrumbs/Breadcrumbs.story.tsx
  packages/palette/src/elements/Breadcrumbs/Breadcrumbs.test.tsx
  packages/palette/src/elements/Breadcrumbs/Breadcrumbs.tsx
  packages/palette/src/elements/Breadcrumbs/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor

#874 chore(stories): adds tabs/stepper stories
  packages/palette/src/elements/BaseTabs/BaseTab.story.tsx
  packages/palette/src/elements/Stepper/Stepper.story.tsx
  packages/palette/src/elements/Stepper/Stepper.tsx
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/elements/Tabs/Tabs.story.tsx
Labels: Merge On Green, Version: Trivial

#875 refactor(tabs,stepper): refactors to utilize basetabs
  packages/palette/src/elements/BaseTabs/BaseTab.tsx
  packages/palette/src/elements/Stepper/Stepper.story.tsx
  packages/palette/src/elements/Stepper/Stepper.tsx
  packages/palette/src/elements/Stepper/__tests__/Stepper.test.tsx
  packages/palette/src/elements/Stepper/index.ts
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
  packages/palette/src/elements/Tabs/__tests__/Tabs.test.tsx
  packages/palette/src/elements/Tabs/index.ts
  packages/palette/src/helpers/flattenChildren.ts
Labels: Version: Patch, canary

#876 [v3] Tabs, Stepper
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/BaseTabs/BaseTab.tsx
  packages/palette/src/elements/BaseTabs/BaseTabs.story.tsx
  packages/palette/src/elements/BaseTabs/BaseTabs.tsx
  packages/palette/src/elements/BaseTabs/tokens/v2.tsx
  packages/palette/src/elements/BaseTabs/tokens/v3.tsx
  packages/palette/src/elements/Stepper/Stepper.story.tsx
  packages/palette/src/elements/Stepper/Stepper.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
  packages/palette/src/themes/Themes.story.tsx
Labels: Version: Minor

#877 [v3] Sup, ProgressBar, CarouselBar, Progress dashes
  packages/palette/src/elements/Carousel/Carousel.story.tsx
  packages/palette/src/elements/CarouselBar/CarouselBar.story.tsx
  packages/palette/src/elements/CarouselBar/CarouselBar.tsx
  packages/palette/src/elements/CarouselBar/index.ts
  packages/palette/src/elements/ProgressBar/ProgressBar.story.tsx
  packages/palette/src/elements/ProgressBar/ProgressBar.tsx
  packages/palette/src/elements/ProgressDots/ProgressDots.story.tsx
  packages/palette/src/elements/ProgressDots/ProgressDots.tsx
  packages/palette/src/elements/ProgressDots/__tests__/ProgressDots.test.tsx
  packages/palette/src/elements/Sup/Sup.story.tsx
  packages/palette/src/elements/Sup/Sup.tsx
  packages/palette/src/elements/Sup/index.ts
  packages/palette/src/elements/Swiper/Swiper.story.tsx
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
  packages/palette/src/elements/Tabs/__tests__/Tabs.test.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/themes/types.ts
  packages/palette/src/themes/v3.tsx
Labels: Version: Minor

#878 [v3] Select
  packages/palette/src/elements/Button/v2/Button.tsx
  packages/palette/src/elements/Grid/Grid.tsx
  packages/palette/src/elements/ProgressBar/ProgressBar.story.tsx
  packages/palette/src/elements/ProgressDots/ProgressDots.story.tsx
  packages/palette/src/elements/Select/Select.story.tsx
  packages/palette/src/elements/Select/Select.test.tsx
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/Select/tokens/types.ts
  packages/palette/src/elements/Select/tokens/v2.ts
  packages/palette/src/elements/Select/tokens/v3.ts
  packages/palette/src/elements/Text/Text.tsx
Labels: Version: Minor

#879 fix(select): fix type signature for deprecated exports
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/Select/__tests__/Select.test.tsx
Labels: Merge On Green, Version: Patch

#880 chore(stories): checks in input stories
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/__tests__/Input.test.tsx
Labels: Merge On Green, Version: Trivial

#881 [v3] Input
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Input/__tests__/Input.test.tsx
  packages/palette/src/elements/Input/tokens/types.ts
  packages/palette/src/elements/Input/tokens/v2.ts
  packages/palette/src/elements/Input/tokens/v3.ts
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/themes/Themes.story.tsx
Labels: Version: Minor

#882 fix(input): corrects input types
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.tsx
Labels: Merge On Green, Version: Patch

#883 Deprecates Sans/Serif; mixes in textTransform to Text
  packages/palette/src/elements/Text/Text.story.tsx
  packages/palette/src/elements/Text/Text.tsx
  packages/palette/src/elements/Typography/Typography.tsx
Labels: Version: Minor

#885 fix(inputs): sets font-family to sans
  packages/palette/src/elements/Input/Input.tsx
Labels: Merge On Green, Version: Patch

#886 fix(divider): resets default styling when presenting as hr
  packages/palette/src/elements/Separator/Separator.story.tsx
  packages/palette/src/elements/Separator/Separator.tsx
Labels: Merge On Green, Version: Patch

#888 ci: Deploy storybooks via Circle orb
  .circleci/config.yml
  .gitignore
  package.json
Labels: Version: Minor

#887 LabeledInput
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.tsx
  packages/palette/src/elements/LabeledInput/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor, canary

#891 feat(helpers): exports shadow constants
  packages/palette/src/helpers/index.ts
Labels: Merge On Green, Version: Minor

#892 fix(labeledinput): allows for clickable labels
  packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.tsx
Labels: Merge On Green, Version: Patch

#893 feat(labeledinput): supports ref
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.tsx
Labels: Merge On Green, Version: Minor

#894 fix(labeledinput): corrects tabindex
  packages/palette/src/elements/LabeledInput/LabeledInput.tsx
Labels: Merge On Green, Version: Patch

#895 fix(select): adjusts padding to accommodate caret
  packages/palette/src/elements/Select/Select.story.tsx
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Patch

#896 feat(expandable): implements expandable
  packages/palette/src/elements/Expandable/Expandable.story.tsx
  packages/palette/src/elements/Expandable/Expandable.tsx
  packages/palette/src/elements/Expandable/index.ts
  packages/palette/src/elements/Toggle/Toggle.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Minor

#897 feat(checkbox): implements v3 styles
  packages/palette/src/elements/Checkbox/Check.story.tsx
  packages/palette/src/elements/Checkbox/Check.tsx
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
  packages/palette/src/elements/Checkbox/Checkbox.tsx
  packages/palette/src/elements/Checkbox/__tests__/Checkbox.test.tsx
  packages/palette/src/elements/Checkbox/tokens/v2.ts
  packages/palette/src/elements/Checkbox/tokens/v3.ts
Labels: Version: Minor, canary
