Repository artsy/palette, pull requests merged in 2021-12, with the labels that each got.

#1080 fix: modal background color
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Version: Minor, Squash On Green

#1081 feat(NX-3032): add space of 20px in xs breakpoint
  packages/palette/src/elements/Modal/Modal.tsx
Labels: Version: Minor, Jira Synced, canary

#1083 feat(modaldialog): implements new modal
  packages/palette-docs/content/docs/elements/Modal.mdx
  packages/palette-docs/content/docs/elements/ModalDialog.mdx
  packages/palette/src/elements/Dialog/Dialog.tsx
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/Modal/ModalBase.tsx
  packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
  packages/palette/src/elements/ModalDialog/ModalDialog.tsx
  packages/palette/src/elements/ModalDialog/ModalDialogContent.story.tsx
  packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx
  packages/palette/src/elements/ModalDialog/index.ts
  packages/palette/src/elements/index.tsx
  packages/palette/src/utils/index.ts
  packages/palette/src/utils/useDidMount.ts
  packages/palette/src/utils/useOnScroll.ts
  packages/palette/src/utils/useSentinelVisibility.tsx
Labels: Version: Minor, canary

#1085 fix: blacklist -> blocklist
  packages/palette/src/svgs/_icons.story.tsx
Labels: Merge On Green, Version: Patch, Future Friday

#1090 feat: exports button variants/mixin
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/index.ts
  packages/palette/src/elements/Button/v3/Button.tsx
Labels: Merge On Green, Version: Minor

#1092 fix(SWA): Fix onEnter in AutocompleteInput
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Version: Patch
