Repository artsy/palette, pull requests merged in 2021-04, with the labels that each got.

#898 feat(radio): implements v3 styles
  packages/palette/src/elements/BorderedRadio/BorderedRadio.story.tsx
  packages/palette/src/elements/BorderedRadio/BorderedRadio.tsx
  packages/palette/src/elements/BorderedRadio/index.ts
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Checkbox/Checkbox.tsx
  packages/palette/src/elements/Radio/Radio.story.tsx
  packages/palette/src/elements/Radio/Radio.tsx
  packages/palette/src/elements/Radio/RadioDot.tsx
  packages/palette/src/elements/Radio/tokens/v2.ts
  packages/palette/src/elements/Radio/tokens/v3.ts
  packages/palette/src/elements/index.tsx
  packages/palette/src/themes/v3.tsx
Labels: Version: Minor, canary

#899 fix(expandable): box props should apply to entire component
  packages/palette/src/elements/Expandable/Expandable.story.tsx
  packages/palette/src/elements/Expandable/Expandable.tsx
Labels: Merge On Green, Version: Patch

#900 fix(theme): corrects media queries
  packages/palette/src/themes/v2.tsx
  packages/palette/src/themes/v3.tsx
Labels: Version: Minor

#901 fix: protects against error on ssr
  packages/palette/src/elements/ReadMore/ReadMore.story.tsx
  packages/palette/src/elements/ReadMore/ReadMore.tsx
Labels: Version: Patch, canary

#903 bugfix: Ensure read more only operates on strings
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx
Labels: Version: Minor

#905 fix(button): updates v3 button styling
  packages/palette/src/elements/Button/v3/tokens.ts
Labels: Merge On Green, Version: Patch

#906 [v3] Pagination
  packages/palette/src/elements/Link/Link.tsx
  packages/palette/src/elements/Pagination/LargePagination.tsx
  packages/palette/src/elements/Pagination/Pagination.story.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
  packages/palette/src/elements/Pagination/SmallPagination.tsx
  packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
  packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx
  packages/palette/src/elements/Pagination/index.tsx
Labels: Version: Minor, canary

#907 fix(pagination): updates copy; adjusts aria
  packages/palette/src/elements/Pagination/Pagination.story.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
Labels: Merge On Green, Version: Patch

#908 fix(pagination): fixes last page error
  packages/palette/src/elements/Pagination/Pagination.story.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
Labels: Merge On Green, Version: Patch

#909 fix(pagination): removes extraneous padding
  packages/palette/src/elements/Pagination/Pagination.tsx
Labels: Merge On Green, Version: Patch

#910 fix(pagination): correctly disables next/prev
  packages/palette/src/elements/Pagination/Pagination.story.tsx
  packages/palette/src/elements/Pagination/Pagination.tsx
  packages/palette/src/elements/Pagination/SmallPagination.tsx
  packages/palette/src/elements/Pagination/__tests__/Pagination.test.tsx
  packages/palette/src/elements/Pagination/__tests__/SmallPagination.test.tsx
Labels: Version: Patch

#911 Fixes unstyled text when using interpolation/fragments
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
  packages/palette/src/elements/Checkbox/Checkbox.tsx
  packages/palette/src/elements/Expandable/Expandable.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.tsx
  packages/palette/src/elements/Radio/Radio.tsx
  packages/palette/src/helpers/__tests__/isText.test.tsx
  packages/palette/src/helpers/isText.tsx
Labels: Version: Minor

#912 feat(theme): allows theme to be easily swapped
  packages/palette/src/Theme.tsx
Labels: Version: Minor

#913 feat(types): exports ColumnSpan/Start type
  packages/palette/src/elements/GridColumns/index.ts
Labels: Merge On Green, Version: Minor

#914 fix(expandable): bumps chevron over 10px in v3
  packages/palette/src/elements/Expandable/Expandable.tsx
Labels: Version: Patch
