Repository artsy/palette, pull requests merged in 2021-02, with the labels that each got.

#846 feat: Add chevronSize prop to Toggle component
  packages/palette-docs/content/docs/elements/layout/Toggle.mdx
  packages/palette/src/elements/Toggle/Toggle.tsx
  packages/palette/src/elements/Toggle/__tests__/Toggle.test.tsx
Labels: Version: Minor

#847 Use full 6 digits for hex colors
  packages/palette-tokens/src/index.ts
Labels: Version: Minor

#848 lowercase for better readability
  packages/palette-tokens/src/index.ts
Labels: Version: Minor

#851 Adds Money Icon
  packages/palette/src/svgs/MoneyFillIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#854 chore(checkbox): adds stories for checkbox
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
Labels: Merge On Green, Version: Trivial

#855 fix(checkbox): makes checkbox accessible; supports box props
  packages/palette/src/elements/Checkbox/Check.tsx
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
  packages/palette/src/elements/Checkbox/Checkbox.tsx
  packages/palette/src/elements/Clickable/Clickable.tsx
Labels: Version: Minor

#856 Revert "fix(checkbox): makes checkbox accessible; supports box props"
  packages/palette/src/elements/Checkbox/Check.tsx
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
  packages/palette/src/elements/Checkbox/Checkbox.tsx
  packages/palette/src/elements/Clickable/Clickable.tsx
Labels: Version: Patch

#857 fix(checkbox): makes a11y updates without using button
  packages/palette/src/elements/Checkbox/Check.tsx
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
  packages/palette/src/elements/Checkbox/Checkbox.tsx
  packages/palette/src/elements/Checkbox/__tests__/Checkbox.test.tsx
  packages/palette/src/elements/Clickable/Clickable.tsx
Labels: Version: Minor, canary

#858 Change default Clickable type; minor checkbox fix
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
  packages/palette/src/elements/Checkbox/Checkbox.tsx
  packages/palette/src/elements/Checkbox/__tests__/Checkbox.test.tsx
  packages/palette/src/elements/Clickable/Clickable.story.tsx
  packages/palette/src/elements/Clickable/Clickable.tsx
  packages/palette/src/elements/Swiper/Swiper.story.tsx
Labels: Version: Patch, canary

#859 chore(storybook): rewrites some stories with storybook-states
  packages/palette/package.json
  packages/palette/src/elements/Avatar/Avatar.story.tsx
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
  yarn.lock
Labels: Version: Trivial

#860 fix(toggle): supports keyboard accessibility
  packages/palette/src/elements/Toggle/Toggle.story.tsx
  packages/palette/src/elements/Toggle/Toggle.tsx
Labels: Version: Patch

#864 fix: check for empty strings in join
  packages/palette/src/elements/Join/Join.tsx
Labels: Squash On Green, Version: Minor
