Repository artsy/palette, pull requests merged in 2021-08, with the labels that each got.

#992 chore(space,color): deprecates space & color functions
  packages/palette-tokens/src/helpers.ts
  packages/palette/src/helpers/color.ts
  packages/palette/src/helpers/space.ts
Labels: Version: Minor

#991 [GRO-462] Add EarnMoreIcon to icon list
  packages/palette/src/svgs/EarnMoreIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor

#994 feat(input): supports inputs with custom heights
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Input/tokens/v2.ts
  packages/palette/src/elements/Input/tokens/v3.ts
Labels: Version: Minor

#995 fix(labeledinput): correctly threads custom heights
  packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.tsx
  yarn.lock
Labels: Version: Patch

#996 Fix some deploy issues
  packages/palette-docs/babel.config.json
  packages/palette-docs/content/docs/atoms/Color.mdx
  packages/palette-docs/content/docs/atoms/Icons.mdx
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/gatsby-node.js
  packages/palette-docs/package.json
  packages/palette-docs/src/Boot.tsx
  packages/palette-docs/src/components/Sidebar/NavTree.tsx
  packages/palette-docs/src/layouts/MainLayout.tsx
  packages/palette-docs/src/pages/404.tsx
  yarn.lock
Labels: Version: Minor

#998 ci: Fix docs deploy
  .circleci/config.yml
  packages/palette-docs/package.json
Labels: Version: Minor

#999 ci: Use s3-orb to deploy docs
  .circleci/config.yml
Labels: Version: Minor

#1000 docs: Cleanup - fix headers
  packages/palette-docs/content/docs/atoms/Icons.mdx
  packages/palette-docs/content/docs/elements/Button.mdx
  packages/palette-docs/content/docs/elements/Collapse.mdx
  packages/palette-docs/content/docs/elements/DonutChart.mdx
  packages/palette-docs/content/docs/elements/Flex.mdx
  packages/palette-docs/content/docs/elements/Select.mdx
  packages/palette-docs/content/docs/index.mdx
Labels: Version: Minor

#986 feat: implements dropdown
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.tsx
  packages/palette/src/elements/Dropdown/__tests__/Dropdown.test.tsx
  packages/palette/src/elements/Dropdown/index.ts
  packages/palette/src/elements/Popover/Popover.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/helpers/shadow.ts
  packages/palette/src/utils/__tests__/usePosition.test.ts
  packages/palette/src/utils/usePosition.ts
Labels: Version: Minor, canary

#1002 Light cleanup
  packages/palette-docs/content/docs/atoms/Icons.mdx
  packages/palette-docs/content/docs/atoms/Spacing.mdx
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/package.json
  packages/palette-docs/src/components/GlobalComponents.jsx
  packages/palette-docs/src/components/Sidebar/algolia.css
  packages/palette-docs/src/layouts/MainLayout.tsx
  packages/palette-docs/src/utils/getEditUrl.ts
  yarn.lock
Labels: Version: Minor

#1001 chore: docs for algolia docsearch
  packages/palette-docs/README.md
Labels: Version: Minor

#1004 [palette-docs] Upgrade Palette to latest version of Gatsby; some light cleanup
  .vscode/settings.json
  packages/palette-docs/HACKS.md
  packages/palette-docs/content/docs/atoms/Color.mdx
  packages/palette-docs/content/docs/atoms/Typography.mdx
  packages/palette-docs/content/docs/index.mdx
  packages/palette-docs/gatsby-config.js
  packages/palette-docs/package.json
  packages/palette-docs/src/Boot.tsx
  packages/palette-docs/src/components/ArtsyCodeTheme.tsx
  packages/palette-docs/src/components/CodeEditor.tsx
  packages/palette-docs/src/components/ColorComponent.tsx
  packages/palette-docs/src/components/GlobalStyles.tsx
  packages/palette-docs/src/components/MDXComponents.tsx
  packages/palette-docs/src/components/Playground.jsx
  packages/palette-docs/src/layouts/MainLayout.tsx
  packages/palette-docs/src/utils/playgroundHastPlugin.js
  packages/palette-docs/src/utils/useScrollToSection.ts
  packages/palette-tokens/src/themes/v3.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
  yarn.lock
Labels: Version: Minor

#1005 feat: [palette-docs] Add table of contents to sidebar
  packages/palette-docs/content/docs/atoms/Color.mdx
  packages/palette-docs/content/docs/atoms/Spacing.mdx
  packages/palette-docs/content/docs/atoms/Typography.mdx
  packages/palette-docs/content/docs/elements/Button.mdx
  packages/palette-docs/content/docs/elements/CSSGrid.mdx
  packages/palette-docs/content/docs/index.mdx
  packages/palette-docs/src/components/CodeEditor.tsx
  packages/palette-docs/src/components/CodeEditorTheme.tsx
  packages/palette-docs/src/components/GlobalStyles.tsx
  packages/palette-docs/src/components/MDXComponents.tsx
  packages/palette-docs/src/components/MetaTags.tsx
  packages/palette-docs/src/components/Sidebar/NavTree.tsx
  packages/palette-docs/src/components/Sidebar/index.tsx
  packages/palette-docs/src/components/TableOfContents.tsx
  packages/palette-docs/src/layouts/MainLayout.tsx
  packages/palette-docs/src/utils/useScrollSpy.ts
  packages/palette-docs/src/utils/useScrollToSection.ts
Labels: Version: Minor

#1007 fix(text): increases text styles specificity
  packages/palette/src/elements/Text/Text.tsx
Labels: Version: Patch

#1008 fix(text): exports text-transform type
  packages/palette/src/elements/Text/Text.tsx
Labels: Version: Minor

#1009 fix: changes default font to unica; cleans up
  packages/palette/src/helpers/injectGlobalStyles.tsx
Labels: Version: Patch, canary

#1011 docs: Add a how palette works section
  packages/palette-docs/content/docs/guides/how-palette-works.mdx
Labels: Version: Minor

#1013 docs: More docs
  packages/palette-docs/content/docs/elements/BaseTabs.mdx
  packages/palette-docs/content/docs/elements/Tags.mdx
  packages/palette-docs/content/docs/hooks/useClickOutside.mdx
  packages/palette-docs/content/docs/hooks/useCurrentTime.mdx
  packages/palette-docs/content/docs/hooks/useIsomorphicLayoutEffect.mdx
  packages/palette-docs/content/docs/hooks/usePosition.mdx
  packages/palette-docs/content/docs/hooks/useTheme.mdx
  packages/palette-docs/content/docs/hooks/useThemeConfig.mdx
  packages/palette-docs/content/docs/hooks/useUpdateEffect.mdx
  packages/palette-docs/content/docs/utils/Theme.mdx
  packages/palette-docs/content/docs/utils/ThemeProviderV2.mdx
  packages/palette-docs/content/docs/utils/ThemeProviderV3.mdx
  packages/palette-docs/content/docs/utils/flattenChildren.mdx
  packages/palette-docs/content/docs/utils/getThemeConfig.mdx
  packages/palette-docs/content/docs/utils/injectGlobalStyles.mdx
  packages/palette-docs/content/docs/utils/isText.mdx
  packages/palette-docs/content/docs/utils/shadow.mdx
  packages/palette-docs/content/docs/utils/splitProps.mdx
  packages/palette-docs/content/docs/utils/visuallyDisableScrollbar.mdx
  packages/palette/src/utils/useClickOutside.ts
Labels: Merge On Green, Version: Minor

#1015 fix(avatar,entityheader): supports detailed image props
  packages/palette/src/elements/Avatar/Avatar.story.tsx
  packages/palette/src/elements/Avatar/Avatar.test.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  packages/palette/src/elements/EntityHeader/__tests__/EntityHeader.test.tsx
  packages/palette/src/elements/EntityHeader/v3/EntityHeader.tsx
Labels: Version: Minor

#1017 chore: checks in lockfile
  yarn.lock
Labels: Merge On Green, Version: Patch

#1020 fix(pill): fixes multi-line pills
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
Labels: Merge On Green, Version: Patch

#1019 chore(image): removes responsive image; cleans up types
  packages/palette/src/elements/Avatar/Avatar.tsx
  packages/palette/src/elements/Cards/MediumCard.tsx
  packages/palette/src/elements/Cards/SmallCard.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  packages/palette/src/elements/Image/Image.story.tsx
  packages/palette/src/elements/Image/Image.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
Labels: Version: Major, canary

#1012 feat(multiselect): implements multi-select
  packages/palette/src/elements/MultiSelect/MultiSelect.story.tsx
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/MultiSelect/__tests__/MultiSelect.test.tsx
  packages/palette/src/elements/MultiSelect/index.ts
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/Select/tokens/v3.ts
  packages/palette/src/elements/index.tsx
Labels: Merge On Green, Version: Minor, canary

#1027 feat(autocomplete): implements autocomplete
  packages/palette-docs/content/docs/hooks/useWidthOf.mdx
  packages/palette/package.json
  packages/palette/scripts/generate-styles.ts
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInputOption.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInputOptionLabel.tsx
  packages/palette/src/elements/AutocompleteInput/__tests__/Autocomplete.test.tsx
  packages/palette/src/elements/AutocompleteInput/index.ts
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/utils/index.ts
  packages/palette/src/utils/useWidthOf.ts
  yarn.lock
Labels: Version: Minor, canary
