Repository artsy/palette, pull requests merged in 2022-02, with the labels that each got.

#1111 chore(docs): Fix docs by deleting monorepo lockfile
  .gitignore
  .yarnrc
  package.json
  packages/palette-docs/package.json
  packages/palette/.storybook/main.js
  packages/palette/package.json
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Skeleton/Skeleton.tsx
  yarn.lock
Labels: Merge On Green

#1112 feature: Lodash Full
  packages/palette/package.json
  packages/palette/src/elements/FilterSelect/Components/FilterSelectContext.tsx
  packages/palette/src/elements/FilterSelect/FilterSelect.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#1114 fix(storybooks): Hot reloading
  packages/palette/.storybook/main.js
Labels: Version: Minor

#1115 feat(icon-button): implements icon button
  packages/palette-docs/content/docs/elements/Button.mdx
  packages/palette-docs/content/docs/elements/IconButton.mdx
  packages/palette/src/elements/Button/v3/Button.tsx
  packages/palette/src/elements/IconButton/IconButton.story.tsx
  packages/palette/src/elements/IconButton/IconButton.tsx
  packages/palette/src/elements/IconButton/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor

#1116 Docs updates; clean up; fixes
  packages/palette-docs/content/docs/atoms/Spacing.mdx
  packages/palette-docs/content/docs/atoms/Typography.mdx
  packages/palette-docs/content/docs/elements/AutocompleteInput.mdx
  packages/palette-docs/content/docs/elements/Avatar.mdx
  packages/palette-docs/content/docs/elements/Banner.mdx
  packages/palette-docs/content/docs/elements/BorderBox.mdx
  packages/palette-docs/content/docs/elements/Box.mdx
  packages/palette-docs/content/docs/elements/Button.mdx
  packages/palette-docs/content/docs/elements/Cards.mdx
  packages/palette-docs/content/docs/elements/Clickable.mdx
  packages/palette-docs/content/docs/elements/Dropdown.mdx
  packages/palette-docs/content/docs/elements/EntityHeader.mdx
  packages/palette-docs/content/docs/elements/Expandable.mdx
  packages/palette-docs/content/docs/elements/FitlerSelect.mdx
  packages/palette-docs/content/docs/elements/Flex.mdx
  packages/palette-docs/content/docs/elements/Image.mdx
  packages/palette-docs/content/docs/elements/Menu.mdx
  packages/palette-docs/content/docs/elements/MultiSelect.mdx
  packages/palette-docs/content/docs/elements/Pagination.mdx
  packages/palette-docs/content/docs/elements/PasswordInput.mdx
  packages/palette-docs/content/docs/elements/Popover.mdx
  packages/palette-docs/content/docs/elements/ResponsiveBox.mdx
  packages/palette-docs/content/docs/elements/Separator.mdx
  packages/palette-docs/content/docs/elements/ShowMore.mdx
  packages/palette-docs/content/docs/elements/Spacer.mdx
  packages/palette-docs/content/docs/elements/StaticCountdownTimer.mdx
  packages/palette-docs/content/docs/elements/Sup.mdx
  packages/palette-docs/content/docs/elements/Tabs.mdx
  packages/palette-docs/content/docs/elements/Text.mdx
  packages/palette-docs/content/docs/elements/TextArea.mdx
  packages/palette-docs/content/docs/elements/TimeRemaining.mdx
  packages/palette-docs/content/docs/elements/Toasts.mdx
  packages/palette-docs/content/docs/index.mdx
  packages/palette-docs/src/components/CodeEditor.tsx
  packages/palette-docs/src/components/CodeEditorTheme.tsx
  packages/palette-docs/src/components/CodeSnippet.tsx
  packages/palette-docs/src/components/MDXComponents.tsx
  packages/palette-docs/src/components/Sidebar/NavTree.tsx
  packages/palette-docs/src/components/Sidebar/SearchBox.tsx
  packages/palette-docs/src/components/Sidebar/algolia.css
  packages/palette-docs/src/components/Sidebar/index.tsx
  packages/palette-docs/src/components/StatusBadge.tsx
  packages/palette-docs/src/layouts/MainLayout.tsx
  packages/palette/src/elements/Banner/Banner.tsx
  packages/palette/src/elements/BorderBox/BorderBox.tsx
  packages/palette/src/elements/BorderBox/BorderBoxBase.tsx
  packages/palette/src/elements/EntityHeader/v2/EntityHeader.tsx
  packages/palette/src/elements/FilterSelect/FilterSelect.story.tsx
  packages/palette/src/elements/Menu/Menu.tsx
  packages/palette/src/elements/ResponsiveBox/ResponsiveBox.story.tsx
  packages/palette/src/elements/Shelf/ShelfScrollBar.tsx
  packages/palette/src/elements/ShowMore/ShowMore.story.tsx
  packages/palette/src/elements/Spacer/Spacer.tsx
  packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  packages/palette/src/elements/Tags/Tags.tsx
  packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/utils/__tests__/usePosition.test.ts
  packages/palette/src/utils/usePosition.ts
Labels: Version: Patch

#1118 fix(ModalBase): Make SSR friendly
  packages/palette/src/elements/Modal/ModalBase.tsx
Labels: Merge On Green, Version: Patch

#1119 chore(docs): Super minor fixes
  packages/palette-docs/content/docs/index.mdx
  packages/palette-docs/src/components/Sidebar/NavTree.tsx
  packages/palette-docs/src/components/TableOfContents.tsx
Labels: Merge On Green, Docs

#1121 feat(icons): image set icon
  packages/palette-docs/content/docs/atoms/Color.mdx
  packages/palette-docs/content/docs/atoms/Icons.mdx
  packages/palette-docs/src/components/ColorComponent.tsx
  packages/palette/src/svgs/ImageSetIcon.tsx
  packages/palette/src/svgs/_icons.story.tsx
  packages/palette/src/svgs/index.tsx
Labels: Merge On Green, Version: Minor

#1120 Scrolling marquee for black owned galleries project
  packages/palette/src/elements/Marquee/Marquee.story.tsx
  packages/palette/src/elements/Marquee/Marquee.tsx
  packages/palette/src/elements/Marquee/index.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Minor, Jira Synced

#1123 feat: [Icons] Add Google and Apple icons
  packages/palette/src/svgs/AppleIcon.tsx
  packages/palette/src/svgs/GoogleIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Merge On Green, Version: Minor

#1124 docs: Add link to svg optimization tool
  packages/palette-docs/content/docs/atoms/Icons.mdx
Labels: Merge On Green, Version: Trivial

#1122 GRO-770: Added New Cultural Badges Component
  packages/palette/src/elements/Badge/Badge.story.tsx
  packages/palette/src/elements/Badge/Badge.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  packages/palette/src/elements/EntityHeader/v3/EntityHeader.tsx
Labels: Merge On Green, Version: Minor

#1125 chore: move some type declarations to regular deps
  packages/palette-charts/package.json
  packages/palette-docs/package.json
  packages/palette/package.json
  yarn.lock
Labels: Merge On Green, Version: Minor

#1127 Revert "chore: move some type declarations to regular deps"
  packages/palette-charts/package.json
  packages/palette-docs/package.json
  packages/palette/package.json
  yarn.lock
Labels: Squash On Green

#1131 feat: functioning storybooks for palette-charts
  packages/palette-charts/.storybook/main.js
  packages/palette-charts/README.md
  packages/palette-charts/package.json
  packages/palette-charts/src/elements/DonutChart/DonutChart.story.tsx
  yarn.lock
Labels: Version: Trivial

#1133 fix: remove permanent transparency from DonutChart labels
  packages/palette-charts/src/elements/DonutChart/DonutChart.tsx
Labels: Version: Patch, Jira Synced

#1130 fix: tooltip/positioning improvements
  packages/palette-docs/content/docs/hooks/useFocusLock.mdx
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.tsx
  packages/palette/src/elements/Dropdown/__tests__/Dropdown.test.tsx
  packages/palette/src/elements/Modal/ModalBase.tsx
  packages/palette/src/utils/__tests__/useFocusLock.test.tsx
  packages/palette/src/utils/index.ts
  packages/palette/src/utils/useFocusLock.story.tsx
  packages/palette/src/utils/useFocusLock.ts
  packages/palette/src/utils/usePortal.ts
  packages/palette/src/utils/usePosition.ts
Labels: Version: Major, canary

#1134 fix(modal): fixes support for percentage based widths
  packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
  packages/palette/src/elements/ModalDialog/ModalDialog.tsx
Labels: Merge On Green, Version: Patch

#1135 fix(useclickoutside): wait for stack to clear before adding event
  packages/palette/src/elements/Popover/Popover.tsx
  packages/palette/src/utils/useClickOutside.ts
Labels: Version: Patch
