Repository artsy/palette, pull requests merged in 2022-06, with the labels that each got.

#1176 fix(responsivebox): utilize native aspect-ratio property in place of padding-bottom hack
  packages/palette/src/elements/ResponsiveBox/ResponsiveBox.story.tsx
  packages/palette/src/elements/ResponsiveBox/ResponsiveBox.tsx
Labels: Version: Patch

#1180 feat: add ability to open Dropdown by click
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.tsx
Labels: Merge On Green, Version: Minor

#1169 3.1 updates
  packages/palette-tokens/src/themes/v3.tsx
  packages/palette/package.json
  packages/palette/src/elements/Avatar/Avatar.story.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
  packages/palette/src/elements/Avatar/tokens.ts
  packages/palette/src/elements/Badge/Badge.story.tsx
  packages/palette/src/elements/Badge/index.ts
  packages/palette/src/elements/Banner/Banner.tsx
  packages/palette/src/elements/Breadcrumbs/Breadcrumbs.tsx
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Button/Button.test.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Button/index.ts
  packages/palette/src/elements/Button/tokens.ts
  packages/palette/src/elements/Button/types.ts
  packages/palette/src/elements/Button/v2/Button.tsx
  packages/palette/src/elements/Button/v2/tokens.ts
  packages/palette/src/elements/Button/v3/Button.tsx
  packages/palette/src/elements/Button/v3/tokens.ts
  packages/palette/src/elements/Checkbox/Check.story.tsx
  packages/palette/src/elements/Checkbox/Check.tsx
  packages/palette/src/elements/Checkbox/Checkbox.story.tsx
  packages/palette/src/elements/Checkbox/Checkbox.tsx
  packages/palette/src/elements/Checkbox/tokens/v2.ts
  packages/palette/src/elements/Checkbox/tokens/v3.ts
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.story.tsx
  packages/palette/src/elements/EntityHeader/EntityHeader.tsx
  packages/palette/src/elements/EntityHeader/v3/EntityHeader.tsx
  packages/palette/src/elements/IconButton/IconButton.story.tsx
  packages/palette/src/elements/IconButton/IconButton.tsx
  packages/palette/src/elements/IconButton/index.ts
  packages/palette/src/elements/Label/Label.story.tsx
  packages/palette/src/elements/Label/Label.tsx
  packages/palette/src/elements/Label/index.ts
  packages/palette/src/elements/Message/Message.story.tsx
  packages/palette/src/elements/Message/Message.tsx
  packages/palette/src/elements/Modal/ModalBase.story.tsx
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
  packages/palette/src/elements/Pill/tokens.ts
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/elements/Radio/Radio.story.tsx
  packages/palette/src/elements/Radio/Radio.tsx
  packages/palette/src/elements/Radio/RadioDot.tsx
  packages/palette/src/elements/Radio/tokens/v2.ts
  packages/palette/src/elements/Radio/tokens/v3.ts
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Toasts/Toasts.story.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/utils/useFocusLock.story.tsx
Labels: Version: Major, canary

#1183 fix(useportal): guards on removal
  packages/palette/src/utils/usePortal.ts
Labels: Version: Patch

#1185 fix(pills): fixes hover on selected pills
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
Labels: Merge On Green, Version: Patch

#1186 fix(range): adds ability to label each slider
  packages/palette/src/elements/Range/Range.story.tsx
  packages/palette/src/elements/Range/Range.tsx
Labels: Merge On Green, Version: Patch

#1182 feat: 3.1 input updates
  packages/palette/src/elements/Cards/TriptychCard/v3.tsx
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Input/tokens.ts
  packages/palette/src/elements/Input/tokens/types.ts
  packages/palette/src/elements/Input/tokens/v2.ts
  packages/palette/src/elements/Input/tokens/v3.ts
  packages/palette/src/elements/Input/types.ts
  packages/palette/src/elements/MultiSelect/MultiSelect.story.tsx
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/Select/__tests__/Select.test.tsx
  packages/palette/src/elements/Select/tokens.ts
  packages/palette/src/elements/Select/tokens/v2.ts
  packages/palette/src/elements/Select/tokens/v3.ts
  packages/palette/src/elements/Select/types.ts
  packages/palette/src/elements/TextArea/TextArea.story.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx
  packages/palette/src/elements/TextArea/tokens.ts
  packages/palette/src/elements/TextArea/tokens/types.ts
  packages/palette/src/elements/TextArea/tokens/v2.ts
  packages/palette/src/elements/TextArea/types.ts
Labels: Version: Major, canary

#1187 fix(icons): removes hover functionality from wechat icon
  packages/palette/src/svgs/WeChatIcon.tsx
  packages/palette/src/svgs/_icons.story.tsx
Labels: Version: Patch, canary
