Repository artsy/palette, pull requests merged in 2022-03, with the labels that each got.

#1139 fix: removed line height from pill text
  packages/palette/src/elements/Pill/Pill.tsx
Labels: Version: Minor

#1140 fix: modalDialog width
  packages/palette/src/elements/ModalDialog/ModalDialog.tsx
Labels: Version: Minor

#1142 fix(badge): includes in exports
  packages/palette/src/elements/Badge/index.ts
  packages/palette/src/elements/index.tsx
Labels: Merge On Green, Version: Patch

#1143 fix(filterselect): avoids calling onchange on mount
  packages/palette/src/elements/FilterSelect/FilterSelect.tsx
Labels: Merge On Green, Version: Patch

#1144 fix(tabs): cached tabs rendering
  packages/palette/src/elements/BaseTabs/BaseTabs.tsx
  packages/palette/src/elements/Join/Join.tsx
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
Labels: Merge On Green, Version: Patch

#1145 Revert "fix(join): prefers the provided child key; fallsback to index…
  packages/palette/src/elements/Join/Join.tsx
Labels: Merge On Green, Version: Patch

#1146 fix(badge): prevents wrapping; handles truncation on badges
  packages/palette/src/elements/Badge/Badge.story.tsx
  packages/palette/src/elements/Badge/Badge.tsx
Labels: Merge On Green, Version: Patch

#1149 GRO-836: Adding design update for gallery attributes, until further approval on designs met
  packages/palette/src/elements/Badge/Badge.tsx
Labels: Version: Minor

#1150 GRO-836 Update: Marquee with newly decided default coloring
  packages/palette/src/elements/Marquee/Marquee.story.tsx
  packages/palette/src/elements/Marquee/Marquee.tsx
Labels: Merge On Green, Version: Minor, hackathon
