Repository artsy/palette, pull requests merged in 2022-12, with the labels that each got.

#1232 feat: Spacer uses `x`/`y` now
  README.md
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/Dialog/Dialog.tsx
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.story.tsx
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/Modal/ModalBase.story.tsx
  packages/palette/src/elements/ModalDialog/ModalDialogContent.story.tsx
  packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Popover/Popover.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.story.tsx
  packages/palette/src/elements/Range/Range.story.tsx
  packages/palette/src/elements/Skeleton/Skeleton.story.tsx
  packages/palette/src/elements/Spacer/Spacer.story.tsx
  packages/palette/src/elements/Spacer/Spacer.tsx
  packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/Toasts/Toasts.tsx
  packages/palette/src/themes/Themes.story.tsx
Labels: Version: Major, canary

#1235 docs: updates readme
  README.md
  packages/palette/src/svgs/_icons.story.tsx
Labels: Version: Trivial

#1236 fix(modaldialog): addresses long titles; focus-visible close state
  packages/palette/src/elements/ModalDialog/ModalDialogContent.story.tsx
  packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx
  packages/palette/src/elements/Text/Text.tsx
Labels: Merge On Green, Version: Minor
