Repository artsy/palette, pull requests merged in 2022-05, with the labels that each got.

#1157 feat(icon): add new guarantee icon
  packages/palette/src/svgs/GuaranteeIcon.tsx
  packages/palette/src/svgs/index.tsx
Labels: Version: Minor, canary

#1161 feat(icon): add white Guarantee icon
  packages/palette/src/svgs/GuaranteeIcon.tsx
Labels: Version: Minor

#1163 fix(ssr): Fix docs ssr
  packages/palette-docs/package.json
  packages/palette-docs/src/Boot.tsx
  packages/palette-docs/src/layouts/MainLayout.tsx
  yarn.lock
Labels: Merge On Green, Version: Minor

#1162 docs(message): Add missing <Message> component to docs
  packages/palette-docs/content/docs/elements/Message.mdx
Labels: Merge On Green, Version: Minor

#1165 fix(text): updates default variant to v3
  packages/palette/src/elements/Text/Text.tsx
Labels: Merge On Green, Version: Patch

#1166 fix(spinner): supports box props; respects theme
  packages/palette/src/elements/Spinner/Spinner.story.tsx
  packages/palette/src/elements/Spinner/Spinner.tsx
Labels: Version: Patch

#1167 docs(storybook): add notice about our storybooks site
  packages/palette-docs/content/docs/index.mdx
Labels: Merge On Green, Version: Trivial

#1170 chore(docs): Fix broken links
  packages/palette-docs/content/docs/atoms/Spacing.mdx
  packages/palette-docs/content/docs/guides/development.mdx
  packages/palette-docs/content/docs/guides/migration.mdx
  packages/palette-docs/content/docs/index.mdx
  packages/palette-docs/src/layouts/MainLayout.tsx
  packages/palette-docs/src/utils/getEditUrl.ts
  packages/palette-tokens/README.md
Labels: Merge On Green, Docs

#1171 fix(WP-52): search navigates to correct pathname on local
  packages/palette-docs/src/components/Sidebar/SearchBox.tsx
Labels: Version: Trivial, Docs
