Repository artsy/palette, pull requests merged in 2022-10, with the labels that each got.

#1209 fix(types): adds children to types
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/GridColumns/GridColumns.tsx
Labels: Version: Patch

#1210 chore: forward box props to `Popover` component
  packages/palette/src/elements/Popover/Popover.tsx
Labels: Version: Minor

#1211 fix(Box): add gridArea mixin
  packages/palette/src/elements/Box/Box.tsx
Labels: Version: Minor

#1212 fix(shelf): adds label to scrollbar thumb
  packages/palette/src/elements/Shelf/ShelfScrollBar.tsx
Labels: Version: Patch

#1213 fix: removes typography components
  packages/palette-charts/.storybook/preview.js
  packages/palette-charts/src/elements/BarChart/BarChart.story.tsx
  packages/palette-charts/src/elements/BarChart/BarChart.test.tsx
  packages/palette-charts/src/elements/BarChart/BarChart.tsx
  packages/palette-charts/src/elements/DataVis/ChartHoverTooltip.tsx
  packages/palette-charts/src/elements/DataVis/ChartTooltip.tsx
  packages/palette-charts/src/elements/DonutChart/DonutChart.story.tsx
  packages/palette-charts/src/elements/DonutChart/DonutChart.test.tsx
  packages/palette-charts/src/elements/DonutChart/DonutChart.tsx
  packages/palette-charts/src/elements/LineChart/LineChart.test.tsx
  packages/palette-charts/src/elements/LineChart/LineChart.tsx
  packages/palette/src/elements/Colors/Colors.tsx
  packages/palette/src/elements/Colors/index.tsx
  packages/palette/src/elements/Dialog/Dialog.tsx
  packages/palette/src/elements/Dialog/__tests__/Dialog.test.tsx
  packages/palette/src/elements/Menu/Menu.tsx
  packages/palette/src/elements/Menu/index.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.test.tsx
  packages/palette/src/elements/RadioGroup/RadioGroup.tsx
  packages/palette/src/elements/StaticCountdownTimer/StaticCountdownTimer.tsx
  packages/palette/src/elements/TimeRemaining/TimeRemaining.tsx
  packages/palette/src/elements/TimeRemaining/__tests__/TimeRemaining.test.tsx
  packages/palette/src/elements/Toggle/Toggle.tsx
  packages/palette/src/elements/Toggle/__tests__/Toggle.test.tsx
  packages/palette/src/elements/Toggle/index.tsx
  packages/palette/src/elements/Typography/Typography.test.tsx
  packages/palette/src/elements/Typography/Typography.tsx
  packages/palette/src/elements/Typography/determineFontSizes.test.ts
  packages/palette/src/elements/Typography/determineFontSizes.ts
  packages/palette/src/elements/Typography/index.tsx
  packages/palette/src/elements/index.tsx
  packages/palette/src/helpers/index.ts
  packages/palette/src/helpers/typography.ts
Labels: Version: Major, canary

#1214 chore: removes v2 tab
  packages/palette-tokens/README.md
  packages/palette/.storybook/preview.js
  packages/palette/src/elements/Button/Button.story.tsx
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.tsx
  packages/palette/src/elements/Range/Range.story.tsx
  packages/palette/src/platform/README.md
  packages/palette/src/platform/fonts/fontFamily.ts
  packages/palette/src/platform/fonts/index.ts
Labels: Version: Patch

#1216 feat: add ability to pass `onClose` prop for `Popover` component
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/elements/Popover/Popover.tsx
Labels: Version: Minor

#1215 chore: bumps storybook version
  packages/palette/.storybook/main.js
  packages/palette/package.json
  packages/palette/src/elements/Skeleton/Skeleton.tsx
  yarn.lock
Labels: Version: Trivial

#1217 fix: updates react-remove-scroll
  packages/palette/package.json
  packages/palette/src/elements/ModalDialog/ModalDialog.tsx
  packages/palette/src/utils/useDidMount.ts
  yarn.lock
Labels: Version: Major, canary
