Repository artsy/palette, pull requests merged in 2022-01, with the labels that each got.

#1093 toolchain(linting): Add rule-of-hooks
  packages/palette/.eslintrc.js
Labels: Merge On Green, Version: Minor

#1094 security(colors.js): Lock version to 1.4 due to corruption
  packages/palette-charts/package.json
Labels: Merge On Green, Version: Minor

#1099 feat(FilterSelect): Adds new <FilterSelect> component
  .yarnrc
  packages/palette/package.json
  packages/palette/src/elements/FilterSelect/Components/FilterInput.tsx
  packages/palette/src/elements/FilterSelect/Components/FilterSelectContext.tsx
  packages/palette/src/elements/FilterSelect/Components/FilterSelectResultItem.tsx
  packages/palette/src/elements/FilterSelect/FilterSelect.story.tsx
  packages/palette/src/elements/FilterSelect/FilterSelect.test.tsx
  packages/palette/src/elements/FilterSelect/FilterSelect.tsx
  packages/palette/src/elements/FilterSelect/index.tsx
  packages/palette/src/elements/ShowMore/ShowMore.story.tsx
  packages/palette/src/elements/ShowMore/ShowMore.test.tsx
  packages/palette/src/elements/ShowMore/ShowMore.tsx
  packages/palette/src/elements/ShowMore/index.tsx
  yarn.lock
Labels: Version: Minor

#1103 chore(component): export filterselect
  packages/palette/src/elements/index.tsx
Labels: Merge On Green, Version: Minor

#1104 feat(filterselect): Add multiselect option
  packages/palette/src/elements/FilterSelect/Components/FilterSelectContext.tsx
  packages/palette/src/elements/FilterSelect/FilterSelect.story.tsx
  packages/palette/src/elements/FilterSelect/FilterSelect.test.tsx
  packages/palette/src/elements/FilterSelect/FilterSelect.tsx
  packages/palette/src/elements/FilterSelect/index.tsx
Labels: Merge On Green, Version: Minor

#1106 Fix: Center briefcase and page icons
  packages/palette/src/svgs/BriefcaseIcon.tsx
  packages/palette/src/svgs/PageIcon.tsx
Labels: Version: Patch

#1109 fix(usefocuslock): skips -1 tabindex elements
  packages/palette/src/utils/useFocusLock.story.tsx
  packages/palette/src/utils/useFocusLock.ts
Labels: Merge On Green, Version: Patch
