Repository artsy/palette, pull requests merged in 2023-11, with the labels that each got.

#1332 chore(dropdown): adds story conforming to filter ui pattern
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
Labels: Merge On Green, Version: Trivial

#1334 fix(EMI-1560): Add margin-top to elements when the title is present
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
Labels: Version: Patch, Jira Synced

#1333 fix(EMI-1561): Update "*required" color when the element is disabled
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/PhoneInput/PhoneInput.tsx
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/shared/RequiredField.tsx
Labels: Version: Patch, Jira Synced

#1250 feat(CX-3348): Update Input components
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Input/__tests__/Input.test.tsx
  packages/palette/src/elements/Input/tokens.ts
  packages/palette/src/elements/Input/types.ts
  packages/palette/src/elements/Label/Label.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.story.tsx
  packages/palette/src/elements/LabeledInput/LabeledInput.tsx
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/MultiSelect/tokens.ts
  packages/palette/src/elements/PhoneInput/PhoneInput.story.tsx
  packages/palette/src/elements/PhoneInput/PhoneInput.tsx
  packages/palette/src/elements/PhoneInput/__tests__/PhoneInput.test.tsx
  packages/palette/src/elements/PhoneInput/index.ts
  packages/palette/src/elements/PhoneInput/tokens.tsx
  packages/palette/src/elements/Select/Select.story.tsx
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/Select/__tests__/Select.test.tsx
  packages/palette/src/elements/Select/tokens.ts
  packages/palette/src/elements/Select/types.ts
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/TextArea/__tests__/TextArea.test.tsx
  packages/palette/src/elements/TextArea/tokens.ts
  packages/palette/src/elements/TextArea/types.ts
  packages/palette/src/elements/index.tsx
  packages/palette/src/helpers/index.ts
  packages/palette/src/helpers/transition.ts
  packages/palette/src/shared/RequiredField.tsx
  packages/palette/src/themes/Themes.story.tsx
Labels: Version: Major, Jira Synced, canary

#1335 fix(drawer): renders using portal
  packages/palette/src/elements/Drawer/Drawer.tsx
Labels: Version: Patch, canary

#1337 fix(range): correctly sets width when within drawer
  packages/palette/src/elements/Range/Range.story.tsx
  packages/palette/src/elements/Range/Range.tsx
Labels: Merge On Green, Version: Patch
