Repository artsy/palette, pull requests merged in 2023-08, with the labels that each got.

#1305 fix(drawer): Update transition a bit more
  packages/palette/src/elements/Drawer/Drawer.tsx
Labels: Version: Minor

#1306 feat(modaldialog): exposes modal close button
  packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx
Labels: Merge On Green, Version: Minor

#1308 chore: removes deprecated modal and dialog
  packages/palette/src/elements/Dialog/Dialog.story.tsx
  packages/palette/src/elements/Dialog/Dialog.tsx
  packages/palette/src/elements/Dialog/__tests__/Dialog.test.tsx
  packages/palette/src/elements/Dialog/index.tsx
  packages/palette/src/elements/Modal/Modal.story.tsx
  packages/palette/src/elements/Modal/Modal.tsx
  packages/palette/src/elements/Modal/__tests__/Modal.test.tsx
  packages/palette/src/elements/Modal/index.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Major, canary

#1309 feat(autocompleteinput): exposes ref to the underlying input
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Version: Minor

#1311 style(range): fix spurious shadows in mobile Safari
  packages/palette/src/elements/Range/Range.tsx
Labels: Version: Minor
