Repository artsy/palette, pull requests merged in 2023-02, with the labels that each got.

#1251 feat(popover): renders into a portal
  packages/palette/src/elements/Popover/Popover.tsx
Labels: Version: Minor, canary

#1253 fix(popover): threads through z-index to correct element
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/elements/Popover/Popover.tsx
Labels: Merge On Green, Version: Patch

#1256 feat: add `header` prop for `ModalDialogContent`
  packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
  packages/palette/src/elements/ModalDialog/ModalDialog.tsx
  packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx
Labels: Merge On Green, Version: Minor

#1255 feat(tooltip|popover): pointer centering
  packages/palette/src/elements/Pointer/Pointer.tsx
  packages/palette/src/elements/Popover/Popover.tsx
  packages/palette/src/elements/Tooltip/Tooltip.story.tsx
  packages/palette/src/elements/Tooltip/Tooltip.tsx
  packages/palette/src/utils/index.ts
  packages/palette/src/utils/useLatest.ts
  packages/palette/src/utils/usePosition.ts
  packages/palette/src/utils/useResizeObserver.ts
Labels: Version: Minor, canary

#1258 fix(popover,tooltip): fixes default z-index handling
  packages/palette/src/elements/Popover/Popover.tsx
  packages/palette/src/elements/Tooltip/Tooltip.tsx
Labels: Merge On Green, Version: Patch

#1259 feat(popover): supports optionally ignoring outside clicks
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/elements/Popover/Popover.tsx
Labels: Version: Minor, canary

#1261 feat(popover): adds prop to disable focus management
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/elements/Popover/Popover.tsx
Labels: Merge On Green, Version: Minor
