Repository artsy/palette, pull requests merged in 2023-09, with the labels that each got.

#1312 feat(stack): implements stack component
  packages/palette/src/elements/Stack/Stack.story.tsx
  packages/palette/src/elements/Stack/Stack.tsx
  packages/palette/src/elements/Stack/index.ts
  packages/palette/src/elements/index.tsx
Labels: Version: Minor

#1314 feat(pills): adds profile and gray variant; removes artist variant
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
  packages/palette/src/elements/Pill/tokens.ts
  packages/palette/src/themes/Themes.story.tsx
Labels: Version: Major

#1313 fix(range): prevent min from exactly equaling max
  packages/palette/src/elements/Range/Range.tsx
Labels: Version: Minor

#1315 fix(pill): updates profile + gray tokens
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
  packages/palette/src/elements/Pill/tokens.ts
Labels: Merge On Green, Version: Patch
