Repository artsy/palette, pull requests merged in 2023-04, with the labels that each got.

#1279 feat: adding header to AutoCompleteInput component
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Version: Minor

#1280 fix(readmore): corrects clickable areas in expanded state
  packages/palette/src/elements/ReadMore/ReadMore.story.tsx
  packages/palette/src/elements/ReadMore/ReadMore.tsx
  packages/palette/src/elements/ReadMore/__tests__/ReadMore.test.tsx
Labels: Merge On Green, Version: Patch

#1282 fix(tabs): fixes parent re-renders from resetting state
  packages/palette/src/elements/Tabs/Tabs.story.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
  packages/palette/src/utils/index.ts
  packages/palette/src/utils/usePrevious.ts
Labels: Version: Patch

#1284 fix(expandable): better supports multi-line expandable headings
  packages/palette/src/elements/Expandable/Expandable.story.tsx
  packages/palette/src/elements/Expandable/Expandable.tsx
Labels: Merge On Green, Version: Patch

#1285 feat(expandable): adds event callback
  packages/palette/src/elements/Expandable/Expandable.story.tsx
  packages/palette/src/elements/Expandable/Expandable.tsx
Labels: Merge On Green, Version: Minor

#1286 feat(box): supports gap
  packages/palette/src/elements/Box/Box.story.tsx
  packages/palette/src/elements/Box/Box.tsx
Labels: Version: Minor

#1281 feat(CX-3339): New phone input component
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/PhoneInput/PhoneInput.story.tsx
  packages/palette/src/elements/PhoneInput/PhoneInput.tsx
  packages/palette/src/elements/PhoneInput/__tests__/PhoneInput.test.tsx
  packages/palette/src/elements/PhoneInput/index.ts
  packages/palette/src/elements/PhoneInput/tokens.tsx
  packages/palette/src/shared/RequiredField.tsx
Labels: Jira Synced

#1288 fix(range): removes labelled tuple for time being
  packages/palette/src/elements/Range/Range.tsx
Labels: Version: Patch
