Repository artsy/palette, pull requests merged in 2023-12, with the labels that each got.

#1336 chore: support dotted pill
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
  packages/palette/src/elements/Pill/tokens.ts
Labels: Version: Minor, Squash On Green

#1339 chore: Switch useHasEnteredViewport to use IntersectionObserver instead of unreliable logic
  packages/palette-charts/src/elements/BarChart/BarChart.test.tsx
  packages/palette-charts/src/elements/BarChart/BarChart.tsx
  packages/palette-charts/src/elements/DataVis/useIntersectionObserver.ts
  packages/palette-charts/src/elements/DataVis/utils/useHasEnteredViewPort.ts
Labels: Version: Minor

#1343 fix(useposition): handles scrolling within divs
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/utils/__tests__/usePosition.test.ts
  packages/palette/src/utils/usePosition.ts
Labels: Version: Patch

#1344 Revert "fix(useposition): handles scrolling within divs"
  packages/palette/src/elements/Popover/Popover.story.tsx
  packages/palette/src/utils/__tests__/usePosition.test.ts
  packages/palette/src/utils/usePosition.ts
Labels: Merge On Green, Version: Patch
