Repository artsy/palette, pull requests merged in 2023-10, with the labels that each got.

#1318 chore: add NODE_OPTIONS env var to storybook start script
  packages/palette/package.json
Labels: Version: Trivial

#1319 fix(pill): forwards ref to pill
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
Labels: Version: Patch

#1320 fix(pill): corrects x icon behavior
  packages/palette/src/elements/Pill/Pill.tsx
Labels: Merge On Green, Version: Patch

#1324 fix(pill): corrects selected state
  packages/palette/src/elements/Pill/tokens.ts
Labels: Merge On Green, Version: Patch

#1325 feat(pill): supports right side icon positioning
  packages/palette/src/elements/Pill/Pill.story.tsx
  packages/palette/src/elements/Pill/Pill.tsx
Labels: Version: Minor, Jira Synced

#1322 fix(EMI-1373): Fix Select issues with Firefox
  packages/palette/src/elements/Select/Select.story.tsx
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/Select/tokens.ts
Labels: Version: Minor, Jira Synced

#1323 feat(EMI-1371): update MultiSelect components
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/MultiSelect/tokens.ts
Labels: Version: Minor, Jira Synced

#1327 fix: Hide placeholder text for select elements
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/MultiSelect/tokens.ts
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Minor

#1328 fix: Add `value` & `onChange` to Select
  packages/palette/src/elements/Select/Select.tsx
Labels: Version: Minor, Jira Synced

#1329 fix(dia-240): optimize tooltip when inactive
  packages/palette/src/elements/Tooltip/Tooltip.story.tsx
  packages/palette/src/utils/useMutationObserver.ts
  packages/palette/src/utils/usePosition.ts
  packages/palette/src/utils/useResizeObserver.ts
Labels: Version: Patch, Jira Synced

#1330 fix(button): offsets icon for padding balance
  packages/palette/src/elements/Button/Button.tsx
Labels: Version: Patch
