Repository artsy/palette, pull requests merged in 2023-05, with the labels that each got.

#1291 Fixes Types of property 'maxHeight' are incompatible for AutocompleteInput
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Version: Patch

#1294 feat(dev): add yalc for local package dev
  README.md
  packages/palette/package.json
  packages/palette/scripts/yalc-sync-after-change
  packages/palette/tsconfig.json
  yarn.lock
Labels: Version: Minor

#1292 chore(theme): removes v2; v3 default
  packages/palette-charts/.storybook/preview.js
  packages/palette-charts/src/elements/DonutChart/DonutChart.tsx
  packages/palette-tokens/src/index.ts
  packages/palette-tokens/src/text.ts
  packages/palette-tokens/src/themes/index.ts
  packages/palette-tokens/src/themes/types.ts
  packages/palette-tokens/src/themes/v2.tsx
  packages/palette-tokens/src/themes/v3.tsx
  packages/palette-tokens/src/typography/types.ts
  packages/palette-tokens/src/typography/v2.ts
  packages/palette/scripts/generate-styles.ts
  packages/palette/scripts/generate-tokens.ts
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
  packages/palette/src/elements/Banner/Banner.test.tsx
  packages/palette/src/elements/BaseTabs/BaseTabs.story.tsx
  packages/palette/src/elements/BorderBox/BorderBox.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Carousel/CarouselNavigation.tsx
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/EntityHeader/__tests__/EntityHeader.test.tsx
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.story.tsx
  packages/palette/src/elements/Modal/ModalBase.story.tsx
  packages/palette/src/elements/StackableBorderBox/StackableBorderBox.story.tsx
  packages/palette/src/elements/StackableBorderBox/StackableBorderBox.tsx
  packages/palette/src/elements/Toasts/Toasts.story.tsx
  packages/palette/src/helpers/__tests__/color.test.ts
  packages/palette/src/helpers/__tests__/media.test.ts
  packages/palette/src/helpers/__tests__/space.test.ts
  packages/palette/src/helpers/color.ts
  packages/palette/src/helpers/space.ts
  packages/palette/src/themes/Themes.story.tsx
  packages/palette/src/themes/types.ts
  packages/palette/tsconfig.json
  yarn.lock
Labels: Version: Major, canary

#1296 feat: close dropdown when the footer is clicked
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Version: Minor

#1297 chore: reuse handleClose method
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Version: Patch

#1298 fix(autocompleteinput): adjusts height when filtering results
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
  packages/palette/src/utils/__tests__/usePosition.test.ts
  packages/palette/src/utils/usePosition.ts
Labels: Version: Patch, canary

#1299 fix(autocomplete): improves focus management for pointer devices
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
Labels: Version: Patch, Jira Synced

#1300 feat(Drawer): export Drawer element
  packages/palette/src/elements/Drawer/Drawer.tsx
  packages/palette/src/elements/index.tsx
Labels: Version: Minor
