Repository artsy/palette, pull requests merged in 2024-10, with the labels that each got.

#1400 fix: Update color red100 and red10
  packages/palette-tokens/src/themes/v3.tsx
Labels: Version: Minor

#1399 chore(styled-components): upgrade to v6
  .circleci/config.yml
  package.json
  packages/palette-charts/package.json
  packages/palette-charts/src/elements/BarChart/Bar.tsx
  packages/palette-charts/src/elements/LineChart/LineChart.tsx
  packages/palette/package.json
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/Banner/Banner.test.tsx
  packages/palette/src/elements/BaseTabs/BaseTab.tsx
  packages/palette/src/elements/BaseTabs/BaseTabs.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/MultiSelect/tokens.ts
  packages/palette/src/elements/PhoneInput/PhoneInput.tsx
  packages/palette/src/elements/Pill/tokens.ts
  packages/palette/src/elements/Radio/Radio.tsx
  packages/palette/src/elements/Select/Select.tsx
  packages/palette/src/elements/Select/tokens.ts
  packages/palette/src/elements/Skeleton/Skeleton.tsx
  packages/palette/src/elements/Swiper/Swiper.tsx
  packages/palette/src/helpers/injectGlobalStyles.tsx
  yarn.lock
Labels: Version: Major, canary, performance

#1403 ci(storybook): Fix storybook compiles on merge
  .circleci/config.yml
  package.json
Labels: Merge On Green, Version: Trivial

#1404 fix(stackable-box): Fix css specificity on borders
  packages/palette/src/elements/StackableBorderBox/StackableBorderBox.story.tsx
  packages/palette/src/elements/StackableBorderBox/StackableBorderBox.tsx
Labels: Version: Patch, Squash On Green

#1405 fix(input): Fix placeholder visibility
  packages/palette/src/elements/Input/Input.story.tsx
  packages/palette/src/elements/Input/Input.tsx
Labels: Version: Patch

#1406 fix(bordered-radio): more border specificity fixes
  packages/palette/src/elements/BorderedRadio/BorderedRadio.tsx
Labels: Version: Patch

#1407 fix(textarea): Fix placeholder visibility
  packages/palette/src/elements/TextArea/TextArea.tsx
Labels: Version: Patch
