Repository artsy/palette, pull requests merged in 2024-02, with the labels that each got.

#1362 fix(image): prevents ovewriting display style prop
  packages/palette/src/elements/Image/LazyImage.tsx
Labels: Merge On Green, Version: Patch

#1363 fix(yalc): Make sure yalc properly syncs changes to Force
  packages/palette/scripts/yalc-sync-after-change
Labels: Version: Patch

#1364 fix(dropdown): only manage focus when keyboard navigating
  packages/palette/src/elements/Dropdown/Dropdown.tsx
Labels: Version: Patch, Jira Synced

#1366 fix(tooltip): prevent parent from altering font-styles
  packages/palette/src/elements/Tooltip/Tooltip.tsx
Labels: Version: Patch
