Repository artsy/palette, pull requests merged in 2024-12, with the labels that each got.

#1414 fix(bar-chart): Fix init
  packages/palette-charts/package.json
  packages/palette-charts/src/elements/DataVis/useIntersectionObserver.ts
Labels: Merge On Green, Version: Patch, Jira Synced

#1415 feat: adjust and expand red palette
  packages/palette-tokens/src/themes/v3.tsx
  packages/palette-tokens/src/themes/v3Dark.tsx
Labels: Version: Minor

#1416 chore: Move shared deps to peerDeps
  packages/palette-charts/package.json
Labels: Version: Patch
