Repository artsy/palette, pull requests merged in 2024-01, with the labels that each got.

#1350 feat(text): adds xxs tokens
  packages/palette-tokens/src/typography/v3.ts
Labels: Version: Minor

#1352 Revert "fix(useportal): makes safe for ssr"
  packages/palette/src/utils/usePortal.ts
Labels: Version: Patch

#1353 fix(checkbox): moves focus state onto focus-visible
  packages/palette/src/elements/Checkbox/Checkbox.tsx
Labels: Version: Patch

#1356 fix(tooltip): correctly handles positioning edge case by skipping when inactive
  packages/palette/src/elements/Tooltip/Tooltip.story.tsx
  packages/palette/src/utils/usePosition.ts
Labels: Version: Patch

#1357 feat(theme): roughs in a dark theme
  packages/palette-charts/src/elements/DataVis/ChartHoverTooltip.tsx
  packages/palette-tokens/src/themes/index.ts
  packages/palette-tokens/src/themes/v3.tsx
  packages/palette-tokens/src/themes/v3Dark.tsx
  packages/palette/.storybook/preview.js
  packages/palette/src/Theme.tsx
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
  packages/palette/src/elements/Button/tokens.ts
  packages/palette/src/elements/Cards/Card.tsx
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.tsx
  packages/palette/src/elements/HorizontalOverflow/HorizontalOverflow.tsx
  packages/palette/src/elements/Input/tokens.ts
  packages/palette/src/elements/ModalDialog/ModalDialog.tsx
  packages/palette/src/elements/ModalDialog/ModalDialogContent.tsx
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/PhoneInput/PhoneInput.tsx
  packages/palette/src/elements/Pointer/Pointer.tsx
  packages/palette/src/elements/Popover/Popover.tsx
  packages/palette/src/elements/Range/Range.tsx
  packages/palette/src/elements/Shelf/ShelfNavigation.tsx
  packages/palette/src/elements/TextArea/TextArea.tsx
  packages/palette/src/elements/Toasts/Toast.tsx
  packages/palette/src/elements/Tooltip/Tooltip.tsx
  packages/palette/src/helpers/index.ts
  packages/palette/src/helpers/injectGlobalStyles.tsx
  packages/palette/src/helpers/shadow.ts
Labels: Version: Major, canary

#1359 feat: add support for placeHolderURL to Image
  packages/palette/src/elements/Image/Image.story.tsx
  packages/palette/src/elements/Image/Image.tsx
  packages/palette/src/elements/Image/LazyImage.tsx
Labels: Version: Minor, canary

#1361 fix: fixes long press on AutocompleteInputOption
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.tsx
  packages/palette/src/elements/AutocompleteInput/__tests__/Autocomplete.test.tsx
Labels: Version: Patch
