Repository artsy/palette, pull requests merged in 2024-05, with the labels that each got.

#1380 fix(avatar): hides broken image if avatar load fails
  packages/palette/src/elements/Avatar/Avatar.story.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
Labels: Version: Patch

#1381 feat(dropdown): handles potentially overflowing content
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.tsx
Labels: Version: Patch

#1382 chore: allow null | undefined for image prop in Card
  packages/palette/src/elements/Cards/Card.tsx
Labels: Version: Minor

#1383 fix(modaldialog): passes in z-index correctly
  packages/palette/src/elements/ModalDialog/ModalDialog.story.tsx
  packages/palette/src/elements/ModalDialog/ModalDialog.tsx
Labels: Version: Patch

#1384 feat(theme): sets global selection color
  packages/palette/src/helpers/injectGlobalStyles.tsx
Labels: Version: Minor

#1385 fix(phoneinput): fixes for dark mode
  packages/palette/src/elements/PhoneInput/PhoneInput.tsx
  packages/palette/src/elements/PhoneInput/tokens.tsx
Labels: Version: Patch

#1388 fix: improves contrast ratio of black60 in dark mode; default message variant
  packages/palette-tokens/src/themes/v3.tsx
  packages/palette-tokens/src/themes/v3Dark.tsx
  packages/palette/src/elements/Message/Message.tsx
Labels: Version: Patch, canary
