Repository artsy/palette, pull requests merged in 2024-11, with the labels that each got.

#1409 feat: adds option to disable transitions
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.tsx
Labels: Version: Minor

#1411 fix(dropdown): keeps pointer state in sync with visibility
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.tsx
Labels: Version: Patch, canary

#1412 chore(react): Fix deprecations
  packages/palette/package.json
  packages/palette/src/elements/Banner/Banner.tsx
  packages/palette/src/elements/Button/Button.tsx
  packages/palette/src/elements/Input/Input.tsx
  packages/palette/src/elements/Label/Label.tsx
  packages/palette/src/elements/Marquee/Marquee.tsx
  packages/palette/src/elements/Message/Message.tsx
  packages/palette/src/elements/Pill/Pill.tsx
  packages/palette/src/elements/Spinner/Spinner.tsx
  packages/palette/src/elements/Stepper/Stepper.tsx
  packages/palette/src/elements/Tabs/Tabs.tsx
  yarn.lock
Labels: Version: Minor, canary
