Repository artsy/palette, pull requests merged in 2025-07, with the labels that each got.

#1452 fix(stories): prevents layout thrashing
  packages/palette/src/elements/ResponsiveBox/ResponsiveBox.story.tsx
Labels: Version: Trivial

#1453 fix(dia-1404): dropdown fixes
  packages/palette/src/elements/Dropdown/Dropdown.story.tsx
  packages/palette/src/elements/Dropdown/Dropdown.tsx
Labels: Version: Patch

#1457 feat: Adding color props for BarChart and LineChart
  packages/palette-charts/src/elements/BarChart/Bar.tsx
  packages/palette-charts/src/elements/BarChart/BarChart.story.tsx
  packages/palette-charts/src/elements/BarChart/BarChart.tsx
  packages/palette-charts/src/elements/LineChart/Line.tsx
  packages/palette-charts/src/elements/LineChart/LineChart.story.tsx
  packages/palette-charts/src/elements/LineChart/LineChart.tsx
  packages/palette-charts/src/elements/LineChart/LineChartSVG.tsx
  packages/palette-charts/src/elements/LineChart/Point.tsx
  packages/palette/.storybook/main.js
Labels: Version: Minor, Jira Synced, Squash On Green
