Repository artsy/palette, pull requests merged in 2025-05, with the labels that each got.

#1435 fix(dia-1305): fixes initial autocomplete render in safari
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
  packages/palette/src/utils/usePosition.ts
Labels: Version: Patch

#1434 feat(storybooks): Add autofocus table example
  packages/palette/src/elements/AutocompleteInput/AutocompleteInput.story.tsx
Labels: Version: Minor

#1436 fix(avatar): prevents avatar from deforming
  packages/palette/src/elements/Avatar/Avatar.story.tsx
  packages/palette/src/elements/Avatar/Avatar.tsx
Labels: Version: Patch

#1439 fix(image): prevents image collapse when lazyload without geometry
  packages/palette/src/elements/Image/Image.story.tsx
  packages/palette/src/elements/Image/Image.tsx
Labels: Version: Patch, canary

#1438 feat: Display selected options on MultiSelect
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
Labels: Version: Minor

#1441 feat: Add selected onFocus and onBlur props to MultiSelect
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
  packages/palette/src/elements/MultiSelect/__tests__/MultiSelect.test.tsx
Labels: Version: Minor

#1442 fix: MultiSelect onBlur and onVisible
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
Labels: Version: Minor

#1444 fix: MultiSelect selected items check
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
Labels: Version: Minor

#1443 feat: Add autoOpen prop to MultiSelect
  packages/palette/src/elements/MultiSelect/MultiSelect.tsx
Labels: Version: Minor

#1446 fix: Set Drawer `transform` to `none` when opened for fixed children
  packages/palette/src/elements/Drawer/Drawer.tsx
Labels: Version: Minor
